In [63]:
import numpy as np 
import torch 
from torch import autograd


In [64]:
# Usse np.array() to create any matrix 

x = np.array([[1,2,3,4],
     [11,13,15,17],
     [6,9,13,20]])
 #    [22,30,34,29], ])

# 4 samples and 4 features we are testing for 

print(x)

[[ 1  2  3  4]
 [11 13 15 17]
 [ 6  9 13 20]]


In [65]:
x1 = x[:,0].reshape(3,1)
x2 = x[:,1].reshape(3,1)
x3 = x[:,2].reshape(3,1)
x4 = x[:,3].reshape(3,1)

# 4 variables are in columns 

print(x1)
print(x2)
print(x3)
print(x4)

[[ 1]
 [11]
 [ 6]]
[[ 2]
 [13]
 [ 9]]
[[ 3]
 [15]
 [13]]
[[ 4]
 [17]
 [20]]


In [ ]:
# Standard deviation and variances for each variable of data. 
x1_std = np.std(x1)
x1_var = np.var(x1)
x_1_mean = np.mean(x1)
print('x1 standard deviation is ....', x1_std)
print('x1_variance is ....', x1_var)
print('x1 mean is ....', x_1_mean)

x2_std = np.std(x2)
x2_var = np.var(x2)
x_2_mean = np.mean(x2)
print('x2 standard deviation is ... ', x2_std)
print('x2 variance is... ', x2_var)
print('x2 mean is ....', x_2_mean)

x3_std = np.std(x3)
x3_var = np.var(x3)
x_3_mean = np.mean(x3)
print('x3 standard deviation is...',x3_std)
print('x3 varaince is ...', x3_var)
print('x3 mean is ....', x_3_mean)

x4_std = np.std(x4)
x4_var = np.var(x4)
x_4_mean = np.mean(x4)
print('x4 standard deviation is...',  x4_std)
print('x4 variance is ...', x4_var)
print('x4 mean is ...', x_4_mean)


x1 standard deviation is .... 4.08248290463863
x1_variance is .... 16.666666666666668
x1 mean is .... 6.0
x2 standard deviation is ...  4.546060565661952
x2 variance is...  20.666666666666668
x2 mean is .... 8.0
x3 standard deviation is... 5.2493385826745405
x3 varaince is ... 27.555555555555557
x3 mean is .... 10.333333333333334
x4 standard deviation is... 6.944222218666553
x4 variance is ... 48.22222222222222
x4 mean is ... 13.666666666666666


In [ ]:
def function(x):
  y = (x[0]**3)*(x[1]**2)+3*(x[2]**3)*(x[3]**2)
# y = (x1**3)*(x2**2) + 3*(x3**3)*x4**2
  return y

In [ ]:
y_l = np.zeros(shape = ( 3, 1))

for i in range(x.shape[0]):
  y_l[i] = function(x[i])

print(y_l)

[[1.300000e+03]
 [3.151064e+06]
 [2.653896e+06]]


In [ ]:
# def y_function(x):
#   y = (x[:,0]**3)*(x[:,1]**2)+3*(x[:,2]**3)*(x[:,3]**2)
# # y = (x1**3)*(x2**2) + 3*(x3**3)*x4**2
#   return y

In [ ]:
# y_p = y_function(x)
# print(y_p)

In [ ]:
y_std = np.std(y_l)
y_var = np.var(y_l)
y_mean = np.mean(y_l)
print('y standard deviation is...',  y_std)
print('y varaince is ...', y_var)
print('y mean is ....', y_mean)


y standard deviation is... 1382608.4371833794
y varaince is ... 1911606090570.6667
y mean is .... 1935420.0


In [ ]:
# First order derivatives numpy - Done


# Second Order Derivatives numpy - Done 


# Apply normalization. 


# Check with pytorch. Using jacobian and hessian. 


# Check results are the same for numpy and pytorch. 

# Then apply normalisation in the main code base as they would be same results. 



In [ ]:
f_o = np.zeros(shape = (3,4))
f_o.shape
#print(f_o)
def first_order(x):
  f_o[:,0] = 3*(x[:,0]**2)*(x[:,1]**2)
  f_o[:,1] = 2*(x[:,0]**3)*x[:,1]
  f_o[:,2] = 9 * (x[:,2]**2)*(x[:,3]**2)
  f_o[:,3] = 6*(x[:,2]**3)*x[:,3]

  return f_o


In [ ]:
f_o_un = first_order(x)
print(f_o_un) # values are correct 

[[1.20000e+01 4.00000e+00 1.29600e+03 6.48000e+02]
 [6.13470e+04 3.46060e+04 5.85225e+05 3.44250e+05]
 [8.74800e+03 3.88800e+03 6.08400e+05 2.63640e+05]]


In [ ]:

#print(s_o)

def second_order(x):
  s_o = np.zeros(shape = (3,4,4))

  # second orders relating to x1
  s_o[:,0,0] = 6*(x[:,0])*(x[:,1]**2)
  s_o[:,0,1] = 6*(x[:,0]**2)*(x[:,1])
  s_o[:,0,2] = 0 
  s_o[:,0,3] = 0 

  # Second Orders relating to x2. 
  s_o[:,1,0] = 6*(x[:,0]**2)*x[:,1]
  s_o[:,1,1] = 2*(x[:,0]**3)
  s_o[:,1,2] = 0 
  s_o[:,1,3] = 0 

  # Second Orders relating to x3 
  s_o[:,2,0] = 0 
  s_o[:,2,1] = 0 
  s_o[:,2,2] = 18*x[:,2]*(x[:,3]**2)
  s_o[:,2,3] = 18*(x[:,2]**2)*x[:,3]

  #Second Orders relating to x4
  s_o[:,3,0] = 0 
  s_o[:,3,1] = 0 
  s_o[:, 3, 2] = 18*(x[:,2]**2)*x[:,3]
  s_o[:, 3,3] =  6*(x[:,2]**3)

  return s_o



In [ ]:
s_o_un = second_order(x)
print(s_o_un) # values are correct 

[[[2.4000e+01 1.2000e+01 0.0000e+00 0.0000e+00]
  [1.2000e+01 2.0000e+00 0.0000e+00 0.0000e+00]
  [0.0000e+00 0.0000e+00 8.6400e+02 6.4800e+02]
  [0.0000e+00 0.0000e+00 6.4800e+02 1.6200e+02]]

 [[1.1154e+04 9.4380e+03 0.0000e+00 0.0000e+00]
  [9.4380e+03 2.6620e+03 0.0000e+00 0.0000e+00]
  [0.0000e+00 0.0000e+00 7.8030e+04 6.8850e+04]
  [0.0000e+00 0.0000e+00 6.8850e+04 2.0250e+04]]

 [[2.9160e+03 1.9440e+03 0.0000e+00 0.0000e+00]
  [1.9440e+03 4.3200e+02 0.0000e+00 0.0000e+00]
  [0.0000e+00 0.0000e+00 9.3600e+04 6.0840e+04]
  [0.0000e+00 0.0000e+00 6.0840e+04 1.3182e+04]]]


In [ ]:
# Now normalidation of data on numpy. 

# Do normalisation for X each feature. 
# Do normalization for y. 
# Do normalization for first order. 
# Do normalization for second order. 


In [ ]:
x_1_norm = (x1 - x_1_mean)/ x1_std
print(x_1_norm)

[[-1.22474487]
 [ 1.22474487]
 [ 0.        ]]


In [ ]:

x_nn_1 = np.zeros(shape = (3,1))


for i in range(x_nn_1.shape[0]):
  x_nn_1[i] = (x1[i] - x_1_mean)/x1_std


print(x_nn_1) 

[[-1.22474487]
 [ 1.22474487]
 [ 0.        ]]


Normalisation for feature 1 is done and it checks out. Lets do all the features now. 

In [ ]:
x_2_norm = (x2 - x_2_mean) / x2_std # Normalised feature 2
print(x_2_norm)

[[-1.31982404]
 [ 1.09985336]
 [ 0.21997067]]


In [ ]:
x_nn_2 = np.zeros(shape = (3,1))

for i in range(x_nn_2.shape[0]):
  x_nn_2[i] = (x2[i] - x_2_mean)/x2_std

print(x_nn_2) 

[[-1.31982404]
 [ 1.09985336]
 [ 0.21997067]]


Feature 2 done. 


In [ ]:
x_3_norm = (x3 - x_3_mean) / x3_std # Normalised feature 2
print(x_3_norm)

[[-1.3970014 ]
 [ 0.88900089]
 [ 0.50800051]]


In [ ]:
x_nn_3 = np.zeros(shape = (3,1))

for i in range(x_nn_3.shape[0]):
  x_nn_3[i] = (x3[i] - x_3_mean)/x3_std


print(x_nn_3) 

[[-1.3970014 ]
 [ 0.88900089]
 [ 0.50800051]]


Feature 3 done

In [ ]:
x_4_norm = (x4 - x_4_mean) / x4_std # Normalised feature 2
print(x_4_norm)

[[-1.39204455]
 [ 0.48001536]
 [ 0.91202919]]


In [ ]:
x_nn_4 = np.zeros(shape = (3,1))

for i in range(x_nn_4.shape[0]):
  x_nn_4[i] = (x4[i] - x_4_mean)/x4_std


print(x_nn_4) 

[[-1.39204455]
 [ 0.48001536]
 [ 0.91202919]]


Feature 4 is done. 


In [ ]:
print(x_1_norm)
print(x_2_norm)
print(x_3_norm)
print(x_4_norm)

[[-1.22474487]
 [ 1.22474487]
 [ 0.        ]]
[[-1.31982404]
 [ 1.09985336]
 [ 0.21997067]]
[[-1.3970014 ]
 [ 0.88900089]
 [ 0.50800051]]
[[-1.39204455]
 [ 0.48001536]
 [ 0.91202919]]


In [ ]:
x_norm = np.column_stack([x_1_norm, x_2_norm, x_3_norm, x_4_norm])
print(x_norm) 

# Normalized values for x. 

[[-1.22474487 -1.31982404 -1.3970014  -1.39204455]
 [ 1.22474487  1.09985336  0.88900089  0.48001536]
 [ 0.          0.21997067  0.50800051  0.91202919]]


Normalise Labels

In [ ]:
y_norm = (y_l - y_mean)/ y_std
print(y_norm)

[[-1.39889209]
 [ 0.87923954]
 [ 0.51965255]]


In [ ]:
y_nn = np.zeros(shape =(3,1))

for i in range(y_nn.shape[0]):
  y_nn[i] = (y_l[i] - y_mean)/y_std

print(y_nn)

[[-1.39889209]
 [ 0.87923954]
 [ 0.51965255]]


y is normalized, now we normalise the derivatives. 

First order Normalisation. 



In [ ]:
f_o_un

print(f_o_un)


# First column is multiplied by sigma_1 / sigma_y 

# Second Column is multiplied by sigma_2 / sigma_y 

# Third Column is multiplied by sigma_3 / sigma_y 

# Fourth column is multiplie dby sigma_4 / sigma_y 


dy_dx1_n_factor = x1_std / y_std

dy_dx2_n_factor = x2_std / y_std 

dy_dx3_n_factor = x3_std / y_std 

dy_dx4_n_factor = x4_std / y_std 


print(dy_dx1_n_factor)
print(dy_dx2_n_factor)
print(dy_dx3_n_factor)
print(dy_dx4_n_factor)




[[1.20000e+01 4.00000e+00 1.29600e+03 6.48000e+02]
 [6.13470e+04 3.46060e+04 5.85225e+05 3.44250e+05]
 [8.74800e+03 3.88800e+03 6.08400e+05 2.63640e+05]]
2.9527397597510527e-06
3.288031841410638e-06
3.796692137484986e-06
5.0225516002297625e-06


In [ ]:
f_o_norm_1 = np.zeros(shape = (3,1))
f_o_norm_2 = np.zeros(shape = (3,1))
f_o_norm_3 = np.zeros(shape = (3,1))
f_o_norm_4 = np.zeros(shape = (3,1))

f_o_norm_1 = dy_dx1_n_factor* f_o_un[:,0].reshape(3,1)
f_o_norm_2 = dy_dx2_n_factor*f_o_un[:,1].reshape(3,1)
f_o_norm_3 = dy_dx3_n_factor*f_o_un[:,2].reshape(3,1)
f_o_norm_4 = dy_dx4_n_factor*f_o_un[:,3].reshape(3,1)
print(f_o_norm_1)
print(f_o_norm_2)
print(f_o_norm_3)
print(f_o_norm_4)

f_o_norm = np.zeros(shape = (3,4))

f_o_norm = np.column_stack([f_o_norm_1, f_o_norm_2, f_o_norm_3, f_o_norm_4])

print(f_o_norm)

[[3.54328771e-05]
 [1.81141726e-01]
 [2.58305674e-02]]
[[1.31521274e-05]
 [1.13785630e-01]
 [1.27838678e-02]]
[[0.00492051]
 [2.22191916]
 [2.3099075 ]]
[[0.00325461]
 [1.72901339]
 [1.3241455 ]]
[[3.54328771e-05 1.31521274e-05 4.92051301e-03 3.25461344e-03]
 [1.81141726e-01 1.13785630e-01 2.22191916e+00 1.72901339e+00]
 [2.58305674e-02 1.27838678e-02 2.30990750e+00 1.32414550e+00]]


So f_o norm is first order normalised. 

In [ ]:
# Factors for the second orders to normalise. 


# Do 4 factors for x1 variable. 

# 4 factors for x2 variable. 

# 4 factors for x3 varaible 

# 4 factors for x4 variable. 

# 4x4 16 factors but 6 are the same so 10 only. 


In [67]:
# Diagonals

d2y_d2x1_factor = (x1_var)/ y_std # [0][0] position

d2y_d2x2_factor = (x2_var)/ y_std# [1][1] position

d2y_d2x3_factor = (x3_var)/ y_std # [2][2] position

d2y_d2x4_factor = (x4_var)/y_std # [3][3] position 

# Symmetries of 1 done

d2y_dx1dx2_factor = (x1_std*x2_std) / y_std # accounts for [0][1] and [1][0] position in the 4x4 as it is dx1dx2  and dx2dx1

d2y_dx1dx3_factor = (x1_std*x3_std) / y_std # accunts for [0][2] and the [2][0] position for dx1dx3 and dx3dx1

d2y_dx1dx4_factor = (x1_std*x4_std) / y_std # accounts for [0][3] and the [3][0] positin for dx1 and dx4 

# (2,3)  ( 2,4)  (4,3) remainng symmetires after 1. Done

d2y_dx2dx3_factor =  (x2_std* x3_std) / y_std # accounts for [2][1] and [1][2] positions for dx3dx2 and dx2dx3 

d2y_dx2dx4_factor =  (x2_std* x4_std) / y_std  # accounts for [3][1] and [1][3] position for dx2dx4 and dx4dx2

d2y_dx3dx4_factor =  (x3_std* x4_std) / y_std  # accounts for for [3][2] and [2][3] position for dx3dx4 and dx4dx3 







In [68]:
s_o_un # 3 hessians 

array([[[2.4000e+01, 1.2000e+01, 0.0000e+00, 0.0000e+00],
        [1.2000e+01, 2.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 8.6400e+02, 6.4800e+02],
        [0.0000e+00, 0.0000e+00, 6.4800e+02, 1.6200e+02]],

       [[1.1154e+04, 9.4380e+03, 0.0000e+00, 0.0000e+00],
        [9.4380e+03, 2.6620e+03, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.8030e+04, 6.8850e+04],
        [0.0000e+00, 0.0000e+00, 6.8850e+04, 2.0250e+04]],

       [[2.9160e+03, 1.9440e+03, 0.0000e+00, 0.0000e+00],
        [1.9440e+03, 4.3200e+02, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.3600e+04, 6.0840e+04],
        [0.0000e+00, 0.0000e+00, 6.0840e+04, 1.3182e+04]]])

In [69]:
# Global variables do not keep intalised variables outside functions intended use. Keep variables close inside the function. 

def second_order_normalise(p): 
  #Diagonal normalisation 
  p = np.zeros(shape = (x.shape[0],x.shape[1],x.shape[1])) # keep inside. 

  p[:,0,0] = d2y_d2x1_factor *s_o_un[:,0,0]
  p[:,1,1] = d2y_d2x2_factor * s_o_un[:,1,1]
  p[:,2,2] = d2y_d2x3_factor * s_o_un[:, 2,2]
  p[:,3,3] = d2y_d2x4_factor * s_o_un[:,3,3]


  # Normalise relation to x1 variable 
  p[:,0,1] = d2y_dx1dx2_factor* s_o_un[:,0,1]
  p[:,1,0] = d2y_dx1dx2_factor* s_o_un[:,1,0] # Both representing dx1dx2 and dx2dx1 normalisisation 

  p[:,0,2] = d2y_dx1dx3_factor * s_o_un[:,0,2]
  p[:,2,0] = d2y_dx1dx3_factor * s_o_un[:,2,0] # both represent dx1dx3 and dx3dx1 

  p[:,0,3] = d2y_dx1dx4_factor*s_o_un[:,0,3] 
  p[:,3,0] = d2y_dx1dx4_factor*s_o_un[:,3,0]

  # Normalise last combinations 
  p[:, 2, 1] = d2y_dx2dx3_factor* s_o_un[:, 2, 1]
  p[:, 1, 2] = d2y_dx2dx3_factor *s_o_un[:, 1,2] # dx2dx3 and dx3dx2

  p[:, 3, 1 ] = d2y_dx2dx4_factor *s_o_un[:,3,1]
  p[:, 1, 3 ] = d2y_dx2dx4_factor* s_o_un[:,1, 3] #dx4dx2 and dx2dx4 


  p[:, 3, 2] = d2y_dx3dx4_factor*s_o_un[:,3 ,2]
  p[:, 2 ,3] - d2y_dx3dx4_factor*s_o_un[:,2,3]

  return p 



In [70]:
s_o_norm = second_order_normalise(s_o_un)
print(s_o_norm)

[[[2.89308230e-04 1.61080005e-04 0.00000000e+00 0.00000000e+00]
  [1.61080005e-04 2.98951838e-05 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.72196259e-02 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.70845679e-02 5.65018974e-03]]

 [[1.34456000e-01 1.26689424e-01 0.00000000e+00 0.00000000e+00]
  [1.26689424e-01 3.97904896e-02 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.55514746e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.81523534e+00 7.06273717e-01]]

 [[3.51509500e-02 2.60949609e-02 0.00000000e+00 0.00000000e+00]
  [2.60949609e-02 6.45735970e-03 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.86545947e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.60405110e+00 4.59758031e-01]]]


Vectorised way 

In [74]:
s_o_vec_coe = np.zeros(shape = (4,4))
'''

d2y_d2x1_factor = (x1_var)/ y_var # [0][0] position

d2y_d2x2_factor = (x2_var)/ y_var # [1][1] position

d2y_d2x3_factor = (x3_var)/ y_var # [2][2] position

d2y_d2x4_factor = (x4_var)/y_var # [3][3] position 

# Symmetries of 1 done

d2y_dx1dx2_factor = (x1_std*x2_std) / y_var # accounts for [0][1] and [1][0] position in the 4x4 as it is dx1dx2  and dx2dx1

d2y_dx1dx3_factor = (x1_std*x3_std) / y_var # accunts for [0][2] and the [2][0] position for dx1dx3 and dx3dx1

d2y_dx1dx4_factor = (x1_std*x4_std) / y_var # accounts for [0][3] and the [3][0] positin for dx1 and dx4 

# (2,3)  ( 2,4)  (4,3) remainng symmetires after 1. Done

d2y_dx2dx3_factor =  (x2_std* x3_std) / y_var  # accounts for [2][1] and [1][2] positions for dx3dx2 and dx2dx3 

d2y_dx2dx4_factor =  (x2_std* x4_std) / y_var  # accounts for [3][1] and [1][3] position for dx2dx4 and dx4dx2

d2y_dx3dx4_factor =  (x3_std* x4_std) / y_var  # accounts for for [3][2] and [2][3] position for dx3dx4 and dx4dx3 


'''

s_o_vec_coe = [[d2y_d2x1_factor, d2y_dx1dx2_factor, d2y_dx1dx3_factor, d2y_dx1dx4_factor],
               [d2y_dx1dx2_factor, d2y_d2x2_factor, d2y_dx2dx3_factor, d2y_dx2dx4_factor ],
               [d2y_dx1dx3_factor,d2y_dx2dx3_factor, d2y_d2x3_factor, d2y_dx3dx4_factor],
               [d2y_dx1dx4_factor,d2y_dx2dx4_factor, d2y_dx3dx4_factor, d2y_d2x4_factor]]  

print(s_o_vec_coe)

[[1.205450959103045e-05, 1.3423333782466407e-05, 1.5499930745458355e-05, 2.05044810456034e-05], [1.3423333782466407e-05, 1.4947591892877756e-05, 1.725999240617928e-05, 2.2832823768806855e-05], [1.5499930745458355e-05, 1.725999240617928e-05, 1.993012252383701e-05, 2.6365073898559844e-05], [2.05044810456034e-05, 2.2832823768806855e-05, 2.6365073898559844e-05, 3.487771441671476e-05]]


In [76]:
s_o_norm_vec = s_o_vec_coe* s_o_un

print(s_o_norm_vec)


[[[2.89308230e-04 1.61080005e-04 0.00000000e+00 0.00000000e+00]
  [1.61080005e-04 2.98951838e-05 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.72196259e-02 1.70845679e-02]
  [0.00000000e+00 0.00000000e+00 1.70845679e-02 5.65018974e-03]]

 [[1.34456000e-01 1.26689424e-01 0.00000000e+00 0.00000000e+00]
  [1.26689424e-01 3.97904896e-02 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.55514746e+00 1.81523534e+00]
  [0.00000000e+00 0.00000000e+00 1.81523534e+00 7.06273717e-01]]

 [[3.51509500e-02 2.60949609e-02 0.00000000e+00 0.00000000e+00]
  [2.60949609e-02 6.45735970e-03 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.86545947e+00 1.60405110e+00]
  [0.00000000e+00 0.00000000e+00 1.60405110e+00 4.59758031e-01]]]


In [77]:
print(s_o_norm)

[[[2.89308230e-04 1.61080005e-04 0.00000000e+00 0.00000000e+00]
  [1.61080005e-04 2.98951838e-05 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.72196259e-02 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.70845679e-02 5.65018974e-03]]

 [[1.34456000e-01 1.26689424e-01 0.00000000e+00 0.00000000e+00]
  [1.26689424e-01 3.97904896e-02 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.55514746e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.81523534e+00 7.06273717e-01]]

 [[3.51509500e-02 2.60949609e-02 0.00000000e+00 0.00000000e+00]
  [2.60949609e-02 6.45735970e-03 0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.86545947e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 1.60405110e+00 4.59758031e-01]]]


In [ ]:
 # Use vector way 

 s_o_inverse_from_norm = np.linalg.inv(s_o_vec_coe)
 print(s_o_inverse_from_norm)

[[ 9.58712091e+26 -6.89255843e+26 -5.32670170e+26  2.90261328e+26]
 [-6.18970020e+26  6.18970020e+26  0.00000000e+00 -4.13207793e+25]
 [-6.18970020e+26  0.00000000e+00  6.18970020e+26 -1.04007138e+26]
 [ 3.09485010e+26  0.00000000e+00 -1.54742505e+26 -6.49707694e+25]]
