In [2]:
  # Fix the strike price 
# Main thing 
# Create samples such that ;
# '''
# The four variables make a sample x is a data point x = (t, S, r, sigma) is data points. 
# No stable results -> then normalise the varaibles. 
#        t -> (0,2) only discrete number of days / 365. T is measure in years. 
#        S -> (50,150) stock prices. 
#        r -> [0%,1%] 
#        sigma (volatility) -> [0.1%,25%] -> standard deviation of the log of the returns

# '''



In [ ]:
# Work on this one feature at a time.  *

# Let say we want to make 500 samples to be safe. *

# Create 1 feature at a time column by column *

# then stack the columns together to get a matrix that is mxn and is check mate.*

# create pricing function, use jacaboian and hessian to generate the data. 

# Do same procedure for the model. 

# investigate normalization after. Also how to print graphs with epochs and data. 

# Read the black scholes paper-> find ideas to relate to yours. 

In [36]:
import numpy as np
import scipy.stats as si
import sympy as sy
from sympy.stats import Normal, cdf
from sympy import init_printing
init_printing()
import torch 
from torch import autograd

In [84]:
# Set strike price = 100

Strike = 100 # fixed hyper paramters. 

# Our case this is a fixed paramter. 

In [93]:
# stock price

S_t= torch.linspace(50,150, steps = 500) # constant
#print(create.shape[0]) #  500 shapes
#print(create)
# (start , start + (end - start)/steps -1 , ... , start + (steps -2) * (end - start)/steps -1, e
#p = torch.tensor(50+(150-50)/(500-1))
#print(p) # gets second term so this woks and gives what we want. Spaces values between. 
# allocate in fix memory
#print(S_t)

Stock = S_t.view(500,1)
print(Stock)

tensor([[ 50.0000],
        [ 50.2004],
        [ 50.4008],
        [ 50.6012],
        [ 50.8016],
        [ 51.0020],
        [ 51.2024],
        [ 51.4028],
        [ 51.6032],
        [ 51.8036],
        [ 52.0040],
        [ 52.2044],
        [ 52.4048],
        [ 52.6052],
        [ 52.8056],
        [ 53.0060],
        [ 53.2064],
        [ 53.4068],
        [ 53.6072],
        [ 53.8076],
        [ 54.0080],
        [ 54.2084],
        [ 54.4088],
        [ 54.6092],
        [ 54.8096],
        [ 55.0100],
        [ 55.2104],
        [ 55.4108],
        [ 55.6112],
        [ 55.8116],
        [ 56.0120],
        [ 56.2124],
        [ 56.4128],
        [ 56.6132],
        [ 56.8136],
        [ 57.0140],
        [ 57.2144],
        [ 57.4148],
        [ 57.6152],
        [ 57.8156],
        [ 58.0160],
        [ 58.2164],
        [ 58.4168],
        [ 58.6172],
        [ 58.8176],
        [ 59.0180],
        [ 59.2184],
        [ 59.4188],
        [ 59.6192],
        [ 59.8196],


In [80]:
# Time
T = torch.linspace(0,2, steps = 500)
# time for maturity 
#print(t)
Time = t.view(500,1)
print(Time.shape)

torch.Size([500, 1])


In [82]:
# r return the risk rate 
torch.manual_seed(40) # fixes the random generation. 
r = torch.rand(500)/100 # between 0 and 1
#print(r)
# 0% = 0
# 1% = 0.01
#print(r) 
Rate = r.view(500,1)

In [94]:
# volatility 
torch.manual_seed(10) # fixes the random generation. 
si = torch.rand(500)/4 # between 0.1% and 25% 
#print(r)
# 0% = 0
# 1% = 0.01
#print(si)
#print(si.shape)
Sigma = si.view(500,1)
print(sigma) # 500 samples by 1 column

tensor([[0.1145],
        [0.1207],
        [0.0781],
        [0.1538],
        [0.0535],
        [0.1030],
        [0.1734],
        [0.2423],
        [0.1544],
        [0.0826],
        [0.1370],
        [0.1110],
        [0.1760],
        [0.1393],
        [0.1740],
        [0.2462],
        [0.0731],
        [0.1206],
        [0.1537],
        [0.1242],
        [0.1130],
        [0.0144],
        [0.0172],
        [0.0125],
        [0.0027],
        [0.0086],
        [0.0303],
        [0.0123],
        [0.0077],
        [0.1798],
        [0.2017],
        [0.2095],
        [0.1923],
        [0.1674],
        [0.1801],
        [0.0559],
        [0.2375],
        [0.1164],
        [0.2329],
        [0.1633],
        [0.2228],
        [0.2247],
        [0.0989],
        [0.0886],
        [0.1438],
        [0.1197],
        [0.1446],
        [0.1884],
        [0.0273],
        [0.1193],
        [0.0269],
        [0.2457],
        [0.0371],
        [0.1489],
        [0.0908],
        [0

In [92]:
# Stock, Time, Rate ,Sigma -> 4 features (variables)
# Strike
# https://discuss.pytorch.org/t/tensor-stack-or-concatenate/34331/6 - column and concatinate 

X = torch.column_stack([Stock, Time, Rate, Sigma])
print(X)
print(X.shape) # m x n matrix 



tensor([[5.0000e+01, 0.0000e+00, 3.6788e-03, 1.1452e-01],
        [5.0200e+01, 4.0080e-03, 8.6610e-03, 1.2071e-01],
        [5.0401e+01, 8.0160e-03, 1.7371e-03, 7.8125e-02],
        ...,
        [1.4960e+02, 1.9920e+00, 9.6996e-03, 1.3920e-02],
        [1.4980e+02, 1.9960e+00, 9.8660e-03, 1.4207e-01],
        [1.5000e+02, 2.0000e+00, 8.0984e-03, 1.0032e-02]])
torch.Size([500, 4])
