In [ ]:
import numpy as np
import scipy.stats as si
import sympy as sy
from sympy.stats import Normal, cdf
from sympy import init_printing
init_printing()
import torch 
from torch import autograd

In [ ]:
# stock price - between [50,150]
torch.set_printoptions(precision =8) # https://pytorch.org/docs/stable/generated/torch.set_printoptions.html - gives us values for options
a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low , high = 50 , 150 #range of uniform distribution
torch.manual_seed(50) #Fx the values
S_t = torch.distributions.uniform.Uniform(low, high).sample([a,b]) # samples from low and high values. a,b are the dimensions

Stock = S_t.view(500,1)
print(Stock)

tensor([[111.80220032],
        [ 56.86931610],
        [ 88.92752075],
        [ 54.04117584],
        [ 90.13233948],
        [ 64.41630554],
        [ 96.04570770],
        [ 98.76750183],
        [109.26650238],
        [146.33831787],
        [ 62.30023956],
        [ 90.47687531],
        [ 99.84820557],
        [149.87336731],
        [110.48640442],
        [102.29031372],
        [119.73918915],
        [ 75.05101776],
        [ 86.23926544],
        [ 96.20941925],
        [121.45482635],
        [100.58496094],
        [ 55.17937469],
        [ 74.91546631],
        [ 73.95149231],
        [ 92.32867432],
        [ 50.21603012],
        [118.48017883],
        [124.96813965],
        [ 74.88737488],
        [ 84.90193176],
        [ 69.52577972],
        [ 77.92306519],
        [ 75.25825500],
        [ 87.92112732],
        [126.85848999],
        [119.07047272],
        [125.26332855],
        [ 61.83854294],
        [136.98777771],
        [133.91360474],
        [ 55.316

In [ ]:
# Time -[ between 0 and 2]
torch.set_printoptions(precision =8) # fixes the precision
a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low_t , high_t = 0, 730 #range of uniform distribution by number of days [0, 2]Years
torch.manual_seed(56) #Fx the values
t_t= torch.randint(low_t, high_t, size= (500,1) )  # https://pytorch.org/docs/stable/generated/torch.randint.html - generates uniformaly integers

t = t_t / 365 # to get a more reliable spread of results

# time for maturity 
#print(t)
Time = t.view(500,1)
print(Time)

tensor([[0.70958906],
        [1.86849320],
        [1.33424652],
        [0.98082191],
        [1.68219173],
        [1.61917806],
        [0.67397261],
        [0.31780821],
        [1.49863017],
        [0.66575342],
        [0.61095893],
        [1.91780818],
        [1.97260273],
        [0.63287669],
        [0.97534245],
        [1.23013699],
        [1.37260270],
        [0.04109589],
        [0.30136988],
        [1.51232874],
        [0.88767123],
        [1.77534246],
        [0.22739726],
        [1.07123291],
        [0.40000001],
        [0.43835616],
        [1.25205481],
        [0.75068492],
        [0.73698628],
        [0.46301371],
        [1.89589036],
        [1.25753427],
        [1.57808220],
        [1.98082197],
        [1.82191777],
        [1.16712332],
        [0.39178082],
        [1.17808223],
        [1.98082197],
        [0.67123288],
        [1.92054796],
        [0.56712329],
        [1.27123284],
        [1.11780822],
        [1.20821917],
        [0

In [ ]:
torch.set_printoptions(precision =8)
a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low , high = 0 , 0.01 #range of uniform distribution [0%,1%]
torch.manual_seed(12) #Fx the values
r = torch.distributions.uniform.Uniform(low, high).sample([a,b]) # samples from low and high values. a,b are the dimensions

Rate = r.view(500,1)
print(Rate)

tensor([[4.65687457e-03],
        [2.32766801e-03],
        [4.52720979e-03],
        [5.87112224e-03],
        [4.08644741e-03],
        [1.27174496e-03],
        [6.37283502e-03],
        [2.42061797e-03],
        [7.31190434e-03],
        [7.22437864e-03],
        [1.99235324e-03],
        [6.94827130e-03],
        [5.83003275e-03],
        [6.31828606e-03],
        [5.55886095e-03],
        [1.26248889e-03],
        [9.79028828e-03],
        [8.44265614e-03],
        [1.25586870e-03],
        [4.45622066e-03],
        [6.60057040e-03],
        [5.53811202e-04],
        [1.57293794e-03],
        [8.13671853e-03],
        [7.21634692e-03],
        [2.71733408e-03],
        [3.00298259e-03],
        [6.09941641e-03],
        [5.78365196e-03],
        [6.08343352e-03],
        [4.33862861e-03],
        [8.81311484e-03],
        [3.21634160e-03],
        [2.60444102e-03],
        [2.56618438e-03],
        [1.87215803e-03],
        [6.42342679e-03],
        [1.78555842e-03],
        [1.4

In [ ]:
# volatility 
torch.set_printoptions(precision =8)
a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low , high =  0.01, 0.5 #range of uniform distribution [1%,50%]
torch.manual_seed(30) #Fx the values
si = torch.distributions.uniform.Uniform(low, high).sample([a,b]) # samples from low and high values. a,b are the dimensions
# whenevr we want to fix a distribution we just use torch.manual_seed to fix the distribution.
Sigma = si.view(500,1)
print(Sigma) # 500 samples by 1 column

tensor([[0.45136446],
        [0.37571785],
        [0.24109073],
        [0.43814570],
        [0.37272945],
        [0.39416242],
        [0.44834715],
        [0.31567809],
        [0.21952412],
        [0.42262238],
        [0.37526119],
        [0.31288305],
        [0.44524369],
        [0.21224509],
        [0.09566198],
        [0.17789517],
        [0.46948904],
        [0.03023741],
        [0.06520632],
        [0.35164323],
        [0.43923327],
        [0.16499473],
        [0.15645622],
        [0.39350000],
        [0.33004060],
        [0.21681894],
        [0.16430482],
        [0.29492286],
        [0.04216166],
        [0.17939635],
        [0.48239291],
        [0.13202283],
        [0.06754655],
        [0.30037859],
        [0.26165617],
        [0.29191330],
        [0.11104200],
        [0.19413574],
        [0.09844980],
        [0.23884301],
        [0.03428239],
        [0.29210460],
        [0.08245187],
        [0.17941405],
        [0.11591975],
        [0

In [ ]:
# Stock, Time, Rate ,Sigma -> 4 features (variables)
# Strike
# https://discuss.pytorch.org/t/tensor-stack-or-concatenate/34331/6 - column and concatinate 

X = torch.column_stack([Stock, Time, Rate, Sigma])
print(X)
print(X.shape) # m x n matrix 


tensor([[1.11802200e+02, 7.09589064e-01, 4.65687457e-03, 4.51364458e-01],
        [5.68693161e+01, 1.86849320e+00, 2.32766801e-03, 3.75717849e-01],
        [8.89275208e+01, 1.33424652e+00, 4.52720979e-03, 2.41090730e-01],
        ...,
        [5.91279984e+01, 1.78356159e+00, 2.72788946e-03, 4.56600308e-01],
        [9.81553192e+01, 7.06849337e-01, 1.80347974e-03, 2.50396580e-01],
        [1.06527763e+02, 1.70684934e+00, 2.57011596e-03, 3.33363444e-01]])
torch.Size([500, 4])


In [ ]:
X.requires_grad_(True) # graident for backprop activated with requires_grad true
X.retain_grad() # leaf tensor is a root of the tree 

print(X.shape) 

torch.Size([500, 4])


In [ ]:
# non- divident paying asset. 
# P + S - C = K * e^-r(T-t)
# Set strike price = 100

Strike = 100 # fixed hyper paramters. 

# Our case this is a fixed paramter. 

Using Put-Call Pariety

In [ ]:
def euro_vanilla_call(x):
  d1 = (torch.log(x[0] / Strike) + (x[2] + 0.5 * x[3] ** 2) * x[1]) / (x[3] * torch.sqrt(x[1]))
  d2 = (torch.log(x[0] / Strike) + (x[2] - 0.5 * x[3] ** 2) * x[1]) / (x[3] * torch.sqrt(x[1])) # time x[1] with resepct to the time left not time. (- theta)
    
  call_t = (x[0] * torch.distributions.normal.Normal(0,1).cdf(d1) - Strike * torch.exp(-x[2] * x[1]) * torch.distributions.normal.Normal(0,1).cdf(d2))
  
  call = torch.nn.functional.relu(call_t)
  return call

In [ ]:
call_y = torch.zeros(size = (500 , 1) , dtype = torch.double) # samples

for i in range(X.shape[0]):
  call_y[i] = euro_vanilla_call(X[i]) # runs through each row computation. 
# numerical error (take absolute error of the prices and zero) -> take relu 
print(call_y) # M samples dimension all in all. 

tensor([[2.27208824e+01],
        [2.64448738e+00],
        [6.00817680e+00],
        [1.13445139e+00],
        [1.38564720e+01],
        [4.16414928e+00],
        [1.25864067e+01],
        [6.48108292e+00],
        [1.70539360e+01],
        [4.95461197e+01],
        [5.22133350e-01],
        [1.24405594e+01],
        [2.48867950e+01],
        [5.03251038e+01],
        [1.16890182e+01],
        [9.22473145e+00],
        [3.56101418e+01],
        [0.00000000e+00],
        [1.41424825e-05],
        [1.52217827e+01],
        [3.11631203e+01],
        [9.11991882e+00],
        [0.00000000e+00],
        [5.06056213e+00],
        [6.10148430e-01],
        [2.52588081e+00],
        [3.01188324e-04],
        [2.30086517e+01],
        [2.53934784e+01],
        [3.36814523e-02],
        [1.74365559e+01],
        [3.53640914e-02],
        [4.33091819e-03],
        [5.51966286e+00],
        [8.12413025e+00],
        [3.16077194e+01],
        [1.93348999e+01],
        [2.71523514e+01],
        [7.7

In [ ]:
# P = C - S + K*exp(-rate*time)

In [ ]:
put_y = torch.zeros(size = (500 , 1))


put_y =  call_y -X[:,0].view(500,1) +Strike*torch.exp(-X[:,2].view(500,1)*X[:,1].view(500,1))
print(put_y)

# put from the put call pariety


tensor([[ 1.05887794e+01],
        [ 4.53411884e+01],
        [ 1.64784374e+01],
        [ 4.65190797e+01],
        [ 2.30390739e+01],
        [ 3.95421400e+01],
        [ 1.61121025e+01],
        [ 7.63667679e+00],
        [ 6.69763565e+00],
        [ 2.72798920e+00],
        [ 3.81002431e+01],
        [ 2.06399765e+01],
        [ 2.38951492e+01],
        [ 5.26657104e-02],
        [ 6.61903381e-01],
        [ 6.77923584e+00],
        [ 1.45361214e+01],
        [ 2.49142914e+01],
        [ 1.37229069e+01],
        [ 1.83407021e+01],
        [ 9.12408829e+00],
        [ 8.43669128e+00],
        [ 4.47848587e+01],
        [ 2.92772522e+01],
        [ 2.63704176e+01],
        [ 1.00781651e+01],
        [ 4.94089888e+01],
        [ 4.07164764e+00],
        [ 0.00000000e+00],
        [ 2.48650337e+01],
        [ 3.17154408e+01],
        [ 2.94074268e+01],
        [ 2.15749867e+01],
        [ 2.97468433e+01],
        [ 1.97365570e+01],
        [ 4.53096008e+00],
        [ 1.30844116e-02],
 

In [ ]:
# P = K*e**(-rate*Time)*N(-d2) - S*N(-d1)

def euro_vanilla_put(x):
  d1 = (torch.log(x[0] / Strike) + (x[2] + 0.5 * x[3] ** 2) * x[1]) / (x[3] * torch.sqrt(x[1]))
  d2 = (torch.log(x[0] / Strike) + (x[2] - 0.5 * x[3] ** 2) * x[1]) / (x[3] * torch.sqrt(x[1]))
    
  put_t = (Strike*torch.exp(-x[2]*x[1])*torch.distributions.normal.Normal(0,1).cdf(-d2) - x[0]*torch.distributions.normal.Normal(0,1).cdf(-d1))

  put = torch.nn.functional.relu(put_t)
  return put
# https://pytorch.org/docs/stable/distributions.html - Normal( loc,scale)
#https://www.itl.nist.gov/div898/handbook/eda/section3/eda364.htm - loc and scale the same as mean and standard deviation.
# https://pytorch.org/docs/stable/generated/torch.log.html - returns natrual logarithem
# https://pytorch.org/docs/stable/generated/torch.sqrt.html - returns squart root


In [ ]:
put_original = torch.zeros(size = (500 , 1), dtype = torch.double) # samples

for i in range(X.shape[0]):
  put_original[i] = euro_vanilla_put(X[i]) # runs through each row computation. 

print(put_original) # M samples dimension all in all. 

tensor([[1.05887833e+01],
        [4.53411865e+01],
        [1.64784317e+01],
        [4.65190811e+01],
        [2.30390739e+01],
        [3.95421448e+01],
        [1.61121025e+01],
        [7.63667297e+00],
        [6.69763565e+00],
        [2.72799397e+00],
        [3.81002426e+01],
        [2.06399727e+01],
        [2.38951492e+01],
        [5.26702404e-02],
        [6.61906242e-01],
        [6.77923965e+00],
        [1.45361233e+01],
        [2.49142914e+01],
        [1.37229004e+01],
        [1.83407021e+01],
        [9.12408447e+00],
        [8.43669510e+00],
        [4.47848587e+01],
        [2.92772484e+01],
        [2.63704224e+01],
        [1.00781670e+01],
        [4.94089851e+01],
        [4.07164955e+00],
        [0.00000000e+00],
        [2.48650360e+01],
        [3.17154427e+01],
        [2.94074249e+01],
        [2.15749893e+01],
        [2.97468491e+01],
        [1.97365494e+01],
        [4.53096008e+00],
        [1.30842924e-02],
        [1.67889881e+00],
        [3.7

In [ ]:
torch.isclose(put_y, put_original, atol = 1e-4) # 1e-5 is most values that are close.
#https://pytorch.org/docs/stable/generated/torch.isclose.html  # Close to absolute tolerance and relative torelnce check of data with true and false

# precision correct up to e-4 but a few erros after e-5 due to precision problems. 
# 4 numbers that are not close for 5
# But a few more for after 6. 

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        

In [ ]:
# f_o = torch.zeros(size = (500,4))

# # First order DY/DX

# for i in range(X.shape[0]):
#   f_o[i] = torch.autograd.functional.jacobian( euro_vanilla_put, X[i])

# print(f_o.shape) # m samples by n features 
  
# print(f_o)

In [ ]:
# s_o = torch.zeros(size = (500,4,4))

# #Second Order Risk D2Y/ DX2

# for i in range(X.shape[0]):
#   s_o[i] = torch.autograd.functional.hessian(euro_vanilla_put , X[i])

# print(s_o.shape) # m samples by n features by n features .
  
# print(s_o)