In [23]:
  # Fix the strike price 
# Main thing 
# Create samples such that ;
# '''
# The four variables make a sample x is a data point x = (t, S, r, sigma) is data points. 
# No stable results -> then normalise the varaibles. 
#        t -> (0,2) only discrete number of days / 365. T is measure in years. 
#        S -> (50,150) stock prices. 
#        r -> [0%,1%] 
#        sigma (volatility) -> [1%,50%] -> standard deviation of the log of the returns
# We will use uniform distributiom 
# '''



In [24]:
# Work on this one feature at a time.  *

# Let say we want to make 500 samples to be safe. *

# Create 1 feature at a time column by column *

# then stack the columns together to get a matrix that is mxn and is check mate.

# create pricing function, use jacaboian and hessian to generate the data. 

# Do same procedure for the model. 

# investigate normalization after. Also how to print graphs with epochs and data. 

# Read the black scholes paper -> find ideas to relate to yours. 

In [25]:
import numpy as np
import scipy.stats as si
import sympy as sy
from sympy.stats import Normal, cdf
from sympy import init_printing
init_printing()
import torch 
from torch import autograd

In [26]:
# Set strike price = 100

Strike = 100 # fixed hyper paramters. 

# Our case this is a fixed paramter. 

In [33]:
# stock price - between [50,150]

a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low , high = 50 , 150 #range of uniform distribution
torch.manual_seed(50) #Fx the values
S_t = torch.distributions.uniform.Uniform(low, high).sample([a,b]) # samples from low and high values. a,b are the dimensions

Stock = S_t.view(500,1)
print(Stock)

tensor([[111.8022],
        [ 56.8693],
        [ 88.9275],
        [ 54.0412],
        [ 90.1323],
        [ 64.4163],
        [ 96.0457],
        [ 98.7675],
        [109.2665],
        [146.3383],
        [ 62.3002],
        [ 90.4769],
        [ 99.8482],
        [149.8734],
        [110.4864],
        [102.2903],
        [119.7392],
        [ 75.0510],
        [ 86.2393],
        [ 96.2094],
        [121.4548],
        [100.5850],
        [ 55.1794],
        [ 74.9155],
        [ 73.9515],
        [ 92.3287],
        [ 50.2160],
        [118.4802],
        [124.9681],
        [ 74.8874],
        [ 84.9019],
        [ 69.5258],
        [ 77.9231],
        [ 75.2583],
        [ 87.9211],
        [126.8585],
        [119.0705],
        [125.2633],
        [ 61.8385],
        [136.9878],
        [133.9136],
        [ 55.3168],
        [ 67.0496],
        [ 79.1351],
        [106.8239],
        [ 53.7998],
        [ 77.1507],
        [119.8719],
        [ 59.4418],
        [117.1934],


In [32]:
# Time -[ between 0 and 2]

a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low_t , high_t = 0, 730 #range of uniform distribution by number of days [0, 2]Years
torch.manual_seed(56) #Fx the values
t_t= torch.randint(low_t, high_t, size= (500,1) )  # https://pytorch.org/docs/stable/generated/torch.randint.html - generates uniformaly integers

t = t_t / 365 # to get a more reliable spread of results

# time for maturity 
#print(t)
Time = t.view(500,1)
#print(Time)

tensor([[0.7096],
        [1.8685],
        [1.3342],
        [0.9808],
        [1.6822],
        [1.6192],
        [0.6740],
        [0.3178],
        [1.4986],
        [0.6658],
        [0.6110],
        [1.9178],
        [1.9726],
        [0.6329],
        [0.9753],
        [1.2301],
        [1.3726],
        [0.0411],
        [0.3014],
        [1.5123],
        [0.8877],
        [1.7753],
        [0.2274],
        [1.0712],
        [0.4000],
        [0.4384],
        [1.2521],
        [0.7507],
        [0.7370],
        [0.4630],
        [1.8959],
        [1.2575],
        [1.5781],
        [1.9808],
        [1.8219],
        [1.1671],
        [0.3918],
        [1.1781],
        [1.9808],
        [0.6712],
        [1.9205],
        [0.5671],
        [1.2712],
        [1.1178],
        [1.2082],
        [0.6301],
        [0.0082],
        [1.3315],
        [0.8164],
        [1.8795],
        [1.6932],
        [0.0712],
        [1.6301],
        [1.8904],
        [1.9644],
        [0

In [34]:

a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low , high = 0 , 0.01 #range of uniform distribution [0%,1%]
torch.manual_seed(12) #Fx the values
r = torch.distributions.uniform.Uniform(low, high).sample([a,b]) # samples from low and high values. a,b are the dimensions

Rate = r.view(500,1)
print(Rate)

tensor([[4.6569e-03],
        [2.3277e-03],
        [4.5272e-03],
        [5.8711e-03],
        [4.0864e-03],
        [1.2717e-03],
        [6.3728e-03],
        [2.4206e-03],
        [7.3119e-03],
        [7.2244e-03],
        [1.9924e-03],
        [6.9483e-03],
        [5.8300e-03],
        [6.3183e-03],
        [5.5589e-03],
        [1.2625e-03],
        [9.7903e-03],
        [8.4427e-03],
        [1.2559e-03],
        [4.4562e-03],
        [6.6006e-03],
        [5.5381e-04],
        [1.5729e-03],
        [8.1367e-03],
        [7.2163e-03],
        [2.7173e-03],
        [3.0030e-03],
        [6.0994e-03],
        [5.7837e-03],
        [6.0834e-03],
        [4.3386e-03],
        [8.8131e-03],
        [3.2163e-03],
        [2.6044e-03],
        [2.5662e-03],
        [1.8722e-03],
        [6.4234e-03],
        [1.7856e-03],
        [1.4349e-03],
        [7.4904e-03],
        [7.2748e-03],
        [1.6413e-03],
        [3.2731e-03],
        [1.2394e-03],
        [6.1380e-03],
        [4

In [22]:
# volatility 

a,b = 500 ,1 #dimension of the pytorch tensor to be generated
low , high =  0.01, 0.5 #range of uniform distribution [1%,50%]
torch.manual_seed(30) #Fx the values
si = torch.distributions.uniform.Uniform(low, high).sample([a,b]) # samples from low and high values. a,b are the dimensions
# whenevr we want to fix a distribution we just use torch.manual_seed to fix the distribution.
Sigma = si.view(500,1)
print(Sigma) # 500 samples by 1 column

tensor([[0.4514],
        [0.3757],
        [0.2411],
        [0.4381],
        [0.3727],
        [0.3942],
        [0.4483],
        [0.3157],
        [0.2195],
        [0.4226],
        [0.3753],
        [0.3129],
        [0.4452],
        [0.2122],
        [0.0957],
        [0.1779],
        [0.4695],
        [0.0302],
        [0.0652],
        [0.3516],
        [0.4392],
        [0.1650],
        [0.1565],
        [0.3935],
        [0.3300],
        [0.2168],
        [0.1643],
        [0.2949],
        [0.0422],
        [0.1794],
        [0.4824],
        [0.1320],
        [0.0675],
        [0.3004],
        [0.2617],
        [0.2919],
        [0.1110],
        [0.1941],
        [0.0984],
        [0.2388],
        [0.0343],
        [0.2921],
        [0.0825],
        [0.1794],
        [0.1159],
        [0.1430],
        [0.4850],
        [0.4166],
        [0.0313],
        [0.2637],
        [0.1704],
        [0.2162],
        [0.1260],
        [0.1823],
        [0.1882],
        [0

In [36]:
# Stock, Time, Rate ,Sigma -> 4 features (variables)
# Strike
# https://discuss.pytorch.org/t/tensor-stack-or-concatenate/34331/6 - column and concatinate 

X = torch.column_stack([Stock, Time, Rate, Sigma])
print(X)
print(X.shape) # m x n matrix 


tensor([[1.1180e+02, 7.0959e-01, 4.6569e-03, 4.5136e-01],
        [5.6869e+01, 1.8685e+00, 2.3277e-03, 3.7572e-01],
        [8.8928e+01, 1.3342e+00, 4.5272e-03, 2.4109e-01],
        ...,
        [5.9128e+01, 1.7836e+00, 2.7279e-03, 4.5660e-01],
        [9.8155e+01, 7.0685e-01, 1.8035e-03, 2.5040e-01],
        [1.0653e+02, 1.7068e+00, 2.5701e-03, 3.3336e-01]])
torch.Size([500, 4])
