In [ ]:
import numpy as np 
import torch 
import torch.autograd



General Ways to see consistent data 

In [ ]:
np.random.seed(42)
random_numbers = np.random.random(size = 4) # can generate a vector 
random_numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(42)
random_numbers_1 = np.random.random(size = (4,4))  # size choses the dimensions
random_numbers_1  # 4x4 matrix  -> mxn so m samples by n features 

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [ ]:
np.random.seed(42) # Allows all the numbers to be generated by 10 
random_numbers_2 = 10*np.random.random(size = (4,4))  # size choses the dimensions
random_numbers_2  # 4x4 matrix  -> mxn so m samples by n features 


array([[3.74540119, 9.50714306, 7.31993942, 5.98658484],
       [1.5601864 , 1.5599452 , 0.58083612, 8.66176146],
       [6.01115012, 7.08072578, 0.20584494, 9.69909852],
       [8.32442641, 2.12339111, 1.81824967, 1.8340451 ]])

In [ ]:
# np.random.seed((low,high), size = ( , ), )

In [ ]:
np.random.seed(22) # randomly generated 
np.random.randint(10)

5

In [ ]:
# Set up of maths 

In [ ]:
np.random.seed(42) # Allows all the numbers to be generated by 10 
random_numbers_3= 10*np.random.random(size = (2,2))  # size choses the dimensions
random_numbers_3  # 4x4 matrix  -> mxn so m samples by n features 

array([[3.74540119, 9.50714306],
       [7.31993942, 5.98658484]])

In [ ]:
input_vector = random_numbers_3.reshape(-1,1)
input_vector_1 = random_numbers_3.flatten(order='C') # order C is row major
input_vector_2 = random_numbers_3.flatten(order='F') # order F is now column major
print(input_vector) # so clearly se see a 4X1 vector flattened from 
print(input_vector.shape)
print(input_vector_1)
print(input_vector_1.shape) # just a numbers but nataurally a 1x4
print(input_vector_2)
print(input_vector_2.shape) # just a numbers but nataurally a 4x1

[[3.74540119]
 [9.50714306]
 [7.31993942]
 [5.98658484]]
(4, 1)
[3.74540119 9.50714306 7.31993942 5.98658484]
(4,)
[3.74540119 7.31993942 9.50714306 5.98658484]
(4,)


In [ ]:
x = torch.from_numpy(input_vector) # converted numpy array to a tensor 
print(x) 

tensor([[3.7454],
        [9.5071],
        [7.3199],
        [5.9866]], dtype=torch.float64)


**Generation of data and maths begin from here, with Pytorch Technqiues**






In [ ]:
# Viewing data in form and generating labels. Using random_number 4. 
# Inputs

In [ ]:
np.random.seed(42) # Allows all the numbers to be generated by 10 
random_numbers_4= 10*np.random.random(size = (2,1))  # size choses the dimensions
random_numbers_4  # 2x1 vector -> mxn so m samples by n features 

array([[3.74540119],
       [9.50714306]])

In [ ]:
y = 0.0  # Y IS A SCALAR


In [ ]:
# y = (x_1**3)*np.cos(x_2)
def y_function(x_1,x_2):
  y = (x_1**3)*np.cos(x_2)

  return y 


In [ ]:
y_label = y_function(random_numbers_4[0],random_numbers_4[1])
print(y_label) # label produced. 

[-52.36248321]


In [ ]:
# derivatives first order
dy_dx = np.ones(2)
#print(dy_dx.shape)

def first_order(x_1,x_2):
  dy_dx[0] = 3*(x_1**2)*np.cos(x_2)
  dy_dx[1] = (x_1**3)*(-1*np.sin(x_2))

  return dy_dx.reshape(2,1)



In [ ]:
first_order(random_numbers_4[0], random_numbers_4[1] )
# 
#

array([[-41.94142142],
       [  4.32262067]])

In [ ]:
# lets check 

p = 3*(random_numbers_4[0]**2)*np.cos(random_numbers_4[1])
q = (random_numbers_4[0]**3)*(-1*np.sin(random_numbers_4[1]))

print(p)
print(q)
# so computation method works for first order derivatives 

[-41.94142142]
[4.32262067]


In [ ]:
d2y_dx2 = np.ones(shape =(2,2))

In [ ]:
  #dy_dx[0] = 3*(x_1**2)*np.cos(x_2)
  #dy_dx[1] = (x_1**3)*(-1*np.sin(x_2))


# second order derivatives 

#print(d2y_dx2)
def second_order(x_1,x_2):
    d2y_dx2[0][0] = 6 * x_1 * np.cos(x_2)
    d2y_dx2[0][1] = 3 * (x_1**2)* (-np.sin(x_2))
    d2y_dx2[1][0] = 3 * (x_1**2)* (-np.sin(x_2)) 
    d2y_dx2[1][1] = (x_1**3) * (-np.cos(x_2))
  
    return d2y_dx2.reshape(2,2)



In [ ]:
second_order(random_numbers_4[0],random_numbers_4[1]) # 2x2 matrix 

array([[-22.39622369,   3.46234257],
       [  3.46234257,  52.36248321]])

In [ ]:
 # values check out explicitly 
 print(6 * random_numbers_4[0] * np.cos(random_numbers_4[1]))
 print(3 * (random_numbers_4[0]**2)* (-np.sin(random_numbers_4[1])))
 print(3 * (random_numbers_4[0]**2)* (-np.sin(random_numbers_4[1]))) 
 print((random_numbers_4[0]**3) * (-np.cos(random_numbers_4[1])))

 # which gets values of the hessain.

# No lets check with pytorch if this does the same computations 

[-22.39622369]
[3.46234257]
[3.46234257]
[52.36248321]


In [ ]:

# convert numpy to torch 

x_torch = torch.from_numpy(random_numbers_4) # numpy to tensor 
x_torch.requires_grad_(True) # graident for backprop can be done with respect to inputs as True is on.
x_torch.retain_grad() # leaf tensor is a root of the tree 
print(x_torch)
#print(x_torch.shape)

tensor([[3.7454],
        [9.5071]], dtype=torch.float64, requires_grad=True)


In [ ]:
y_t = torch.zeros(1)
#print(y)
def Y_labels(x_1_t,x_2_t):
  y_t = (x_1_t**3)*(torch.cos(x_2_t))
  return y_t



In [ ]:
y_t = Y_labels(x_torch[0], x_torch[1]) # this maps with numpy version

In [ ]:
# Lets test for autograd works 

# first order derivative

y_t.backward() # gradients 
print(x_torch.grad)





tensor([[-41.9414],
        [  4.3226]], dtype=torch.float64)


In [ ]:
x_torch_1 = torch.from_numpy(random_numbers_4) # numpy to tensor 
x_torch_1.requires_grad_(True) # graident for backprop 
x_torch_1.retain_grad() # leaf tensor is a root of the tree 


torch.autograd.functional.hessian(Y_labels , (x_torch_1[0], x_torch_1[1] ))

((tensor([[-22.3962]], dtype=torch.float64),
  tensor([[3.4623]], dtype=torch.float64)),
 (tensor([[3.4623]], dtype=torch.float64),
  tensor([[52.3625]], dtype=torch.float64)))

In [ ]:
x_torch_1 = torch.from_numpy(random_numbers_4) # numpy to tensor 
x_torch_1.requires_grad_(True) # graident for backprop 
x_torch_1.retain_grad() # leaf tensor is a root of the tree 

torch.autograd.functional.jacobian(Y_labels , (x_torch_1[0], x_torch_1[1] )) # jacobian same as first order derivative

(tensor([[-41.9414]], dtype=torch.float64),
 tensor([[4.3226]], dtype=torch.float64))