In [1]:
#  Flow of model
# 1. Data Preprocessing 
# 2. Model.
# 3. Loss/optimization
# 4. Training. 

In [2]:
pip install pytorch-lightning

     |████████████████████████████████| 913 kB 23.6 MB/s 
     |████████████████████████████████| 636 kB 46.3 MB/s 
     |████████████████████████████████| 829 kB 62.9 MB/s 
     |████████████████████████████████| 234 kB 57.4 MB/s 
     |████████████████████████████████| 118 kB 69.6 MB/s 
     |████████████████████████████████| 10.6 MB 54.5 MB/s 
     |████████████████████████████████| 1.3 MB 36.8 MB/s 
     |████████████████████████████████| 294 kB 46.6 MB/s 
     |████████████████████████████████| 142 kB 55.7 MB/s 
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491070 sha256=5db8331c7fb105e5e5fdc9824a1fd38fce2f9688450f6981a909960f59882408
  Stored in directory: /root/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built future
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.5.0
    Uninstalling tensorboard-2.5.0:
      Successfully uninstalled tensorboard-2.5.0
  Attempting uninsta

In [3]:
import numpy as np 
import torch 
import matplotlib.pyplot as plt
import sklearn
import torch.autograd
from torch.utils.data import DataLoader, random_split
from torch import nn
import pytorch_lightning as pl
import torch.nn.functional as F
from torch.optim import SGD
from torch.optim import Adam
import os
from torchvision import datasets, transforms

if torch.cuda.is_available ():
  device = torch.device("cuda")
  print('GPU IS AVAILABLE :D') # Turn on GPU in collab 

else:
  
  device = torch.device("cpu")
  print('GPU not available ')



GPU not available 


Increased/ Customized data set - Training and Validation data 

In [4]:
# Data preprocessing 
np.random.seed(50)
Inputs = 3*np.random.random(size = (300,4)) # can generate m = 300 samples and n = 4 features 
print(Inputs)
print(Inputs.shape)
#nputs_vec = Inputs.reshape(-1,1) # (1200 , 1) column vector 

[[1.48380494 0.68424931 0.76642177 1.18898973]
 [1.13194529 2.98972269 1.2245916  2.31568198]
 [2.28161006 0.93002805 1.03962361 1.05529445]
 ...
 [2.59049077 0.68359399 2.82602449 1.5580974 ]
 [0.56272659 0.21924999 0.22727439 0.6997265 ]
 [0.97621273 1.96945661 1.68518757 2.96951736]]
(300, 4)


In [5]:
x_torch = torch.from_numpy(Inputs) # tensor
x_torch.requires_grad_(True) # graident for backprop 
x_torch.retain_grad() # leaf tensor is a root of the tree 
print(x_torch.shape)

torch.Size([300, 4])


In [6]:
# returns labels
def l_labels(x):
  return x[0]**4 + (x[1])**3 + torch.sin(x[2]) + x[3]**2

In [7]:
y = torch.zeros(size = (300 , 1)) # samples

for i in range(x_torch.shape[0]):
  y[i] = l_labels(x_torch[i])

print(y)

tensor([[  7.2750],
        [ 34.6682],
        [ 29.8801],
        [ 28.1064],
        [ 21.9779],
        [ 12.5350],
        [ 17.0246],
        [ 26.4298],
        [ 27.8286],
        [ 26.4782],
        [ 38.2007],
        [ 71.3598],
        [ 62.8726],
        [  5.2020],
        [  9.0132],
        [  3.6863],
        [ 82.2729],
        [ 67.5295],
        [ 18.7042],
        [ 45.0779],
        [  6.5456],
        [ 67.3668],
        [ 17.8121],
        [ 10.1087],
        [  8.9203],
        [  5.7506],
        [  5.9007],
        [ 28.1545],
        [  9.8109],
        [ 23.8320],
        [ 10.6152],
        [  7.6838],
        [ 57.8538],
        [ 41.5441],
        [ 61.8318],
        [  6.2136],
        [ 38.5793],
        [ 34.1701],
        [  9.3817],
        [ 29.5905],
        [  2.1003],
        [  5.7299],
        [ 15.3771],
        [ 22.5463],
        [  9.0749],
        [ 28.6798],
        [  1.1032],
        [ 88.4932],
        [  1.1635],
        [ 13.3415],


In [8]:
f_o = torch.zeros(size = (300,4))

for i in range(x_torch.shape[0]):
  f_o[i] = torch.autograd.functional.jacobian(l_labels , x_torch[i])

print(f_o.shape)
  
print(f_o)

torch.Size([300, 4])
tensor([[13.0674,  1.4046,  0.7204,  2.3780],
        [ 5.8014, 26.8153,  0.3393,  4.6314],
        [47.5099,  2.5949,  0.5065,  2.1106],
        ...,
        [69.5354,  1.4019, -0.9506,  3.1162],
        [ 0.7128,  0.1442,  0.9743,  1.3995],
        [ 3.7213, 11.6363, -0.1141,  5.9390]])


In [9]:
s_o = torch.zeros(size = (300,4,4))

for i in range(x_torch.shape[0]):
  s_o[i] = torch.autograd.functional.hessian(l_labels , x_torch[i])

print(s_o.shape)
  
print(s_o)

torch.Size([300, 4, 4])
tensor([[[26.4201,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  4.1055,  0.0000,  0.0000],
         [ 0.0000,  0.0000, -0.6936,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  2.0000]],

        [[15.3756,  0.0000,  0.0000,  0.0000],
         [ 0.0000, 17.9383,  0.0000,  0.0000],
         [ 0.0000,  0.0000, -0.9407,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  2.0000]],

        [[62.4689,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  5.5802,  0.0000,  0.0000],
         [ 0.0000,  0.0000, -0.8622,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  2.0000]],

        ...,

        [[80.5277,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  4.1016,  0.0000,  0.0000],
         [ 0.0000,  0.0000, -0.3104,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  2.0000]],

        [[ 3.7999,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  1.3155,  0.0000,  0.0000],
         [ 0.0000,  0.0000, -0.2253,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  2.0000]],

        [[11

In [10]:
print(x_torch.shape) # m =300, n =4 so 300 x 4
print(y.shape) # m = 300
print(f_o.shape) # m =300,, n = 4 so 300 x 4
print(s_o.shape) # m = 300, n = 4, n = 4. 

torch.Size([300, 4])
torch.Size([300, 1])
torch.Size([300, 4])
torch.Size([300, 4, 4])


In [11]:
BATCH_SIZE = 25

In [12]:
# Data Collected and pre-processing 

x = x_torch.type(torch.FloatTensor)
y = y.type(torch.FloatTensor)
f_o = f_o.type(torch.FloatTensor)
s_o = s_o.type(torch.FloatTensor)


# Organise inputs, labels and differential labels in training and validation data set 

# Training to validation split is 5:1 ratio 
# Training data 
x_train = x[:250].to(device) 
#y_train = y[:250].to(device)
f_o_train = f_o[:250].to(device)
s_o_train = s_o[:250].to(device)


# Validation Data 
x_valid = x[250:].to(device)
#y_valid = y[250:].to(device)
f_o_valid = f_o[250:].to(device)
s_o_valid = s_o[250:].to(device)


print(x_train.shape)
#print(y_train.shape)
print(f_o_train.shape)
print(s_o_train.shape)
print(x_valid.shape)
#print(y_valid.shape)
print(f_o_valid.shape)
print(s_o_valid.shape)



# trainset_set = torch.utils.data.TensorDataset(x_train, y_train, dy_dx_train)
# validation_set = torch.utils.data.TensorDataset(x_valid, y_valid, dy_dx_valid)

train_dataset = torch.utils.data.TensorDataset(x_train , f_o_train, s_o_train)
validation_dataset = torch.utils.data.TensorDataset(x_valid, f_o_valid, s_o_valid)


train_dataloader = torch.utils.data.DataLoader(train_dataset , batch_size=BATCH_SIZE , shuffle=False , num_workers =0)
val_dataloader = torch.utils.data.DataLoader(validation_dataset , batch_size = BATCH_SIZE, shuffle = False, num_workers = 0 )


torch.Size([250, 4])
torch.Size([250, 4])
torch.Size([250, 4, 4])
torch.Size([50, 4])
torch.Size([50, 4])
torch.Size([50, 4, 4])


In [13]:
input_size = 4 # x features
hidden_size_1 = 36
hidden_size_2 = 36
output_size = 4 # y output of training 

learning_rate = 0.001 # hyperparameter
num_epochs = 500 # hyperparameter    \ 250 ->  1 epoch
                                      # 250/32 = 6.2...    - > updating my weights every 6 training samples. 
#    SGD, ADAM, RMSPROP AND MORE .    Wi+1 = Wi - lr* gradient L / wrt to W   goes to minimum    -> update weights
#                                     Bi+1 = Bi - lr* gradient L / wrt to B  goes to minimum     -> Update biases 

beta = 1
delta = 1

In [ ]:
# class NeuralNet(nn.Module):
#   def __init__(self, input_size, hidden_size_1, hidden_size_2, output_size): 
#     super(NeuralNet, self).__init__()
#     self.layer_1 = nn.Linear(input_size, hidden_size_1) # linear layer
#     self.layer_2 = nn.Linear(hidden_size_1, hidden_size_2)
#     self.layer_3 = nn.Linear(hidden_size_2, output_size)

# # 3 layer MLP forward pass
#   def forward(self, x):
#     # layer 1
#     x = self.layer_1(x)
#     x = torch.Softplus(x)

#     # layer 2
#     x = self.layer_2(x)
#     x = torch.Softplus(x)

#     # layer 3 
#     x = self.layer_3(x)

#     return  x 




Twin_second_Order Model 

In [14]:
class TwinSecondOrderNetwork(pl.LightningModule):
  
  def __init__(self):
    super(TwinSecondOrderNetwork,self).__init__()
    self.layer_1 = nn.Linear(input_size, hidden_size_1) # linear layer
    self.layer_2 = nn.Linear(hidden_size_1, hidden_size_2)
    self.layer_3 = nn.Linear(hidden_size_2, output_size)

    self.softplus = nn.Softplus()
    self.loss = nn.MSELoss()

    self.automatic_optimization = False # Turn off automatic optimization. Turns off backprop automatically. 

  def forward(self, x):
    # layer 1
    x = self.layer_1(x)
    x = self.softplus(x)

    # layer 2
    x = self.layer_2(x)
    x = self.softplus(x)

    # layer 3 
    x = self.layer_3(x)

    return x


  def training_step(self, train_batch, batch_idx):
    opt = self.optimizers()
    opt.zero_grad()

    x, f_o, s_o = train_batch
    predicted_f_o = self.forward(x)
    # loop over batch
    predicted_s_o = torch.zeros(size=(x.shape[0], 4, 4))
    for i in range(x.shape[0]): # x_shape is the batch size
      predicted_s_o[i] = torch.autograd.functional.jacobian(self.forward, x[i], create_graph=True, strict=True) # https://github.com/pytorch/pytorch/issues/46918 - Can show we need create_graph to be true as it backpropagets through the graph

    loss = beta * self.loss( f_o, predicted_f_o) + delta * self.loss(s_o,  predicted_s_o)

    loss.backward(retain_graph=True) # keeps gradeints the same and not zero. 

    opt.step() # Every batch. 

    self.log('train_loss', loss)
    print(loss)
    return loss
    


  def validation_step(self, val_batch, batch_idx):
    x, f_o, s_o = val_batch
    predicted_f_o = self.forward(x)
    # loop over batch
    predicted_s_o = torch.zeros(size=(x.shape[0], 4 ,4))
    for i in range(x.shape[0]): # x_shape is the batch size
      predicted_s_o[i] = torch.autograd.functional.jacobian(self.forward, x[i], create_graph=True, strict=True)

    loss = beta * self.loss( f_o, predicted_f_o) + delta * self.loss(s_o,  predicted_s_o)
    self.log('val_loss', loss)
   # print( loss)
    return loss


  def configure_optimizers(self):
    return torch.optim.Adam(self.parameters(), lr=1e-3)
   





In [15]:
trainer = pl.Trainer(max_epochs= 50)
# https://www.machinecurve.com/index.php/question/how-to-set-number-of-epochs-in-pytorch-lightning/
model = TwinSecondOrderNetwork() # Trained. 

trainer.fit(model, train_dataloader, val_dataloader)


GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs

  | Name     | Type     | Params
--------------------------------------
0 | layer_1  | Linear   | 180   
1 | layer_2  | Linear   | 1.3 K 
2 | layer_3  | Linear   | 148   
3 | softplus | Softplus | 0     
4 | loss     | MSELoss  | 0     
--------------------------------------
1.7 K     Trainable params
0         Non-trainable params
1.7 K     Total params
0.007     Total estimated model params size (MB)


/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/data_loading.py:323: UserWarning: The number of training samples (10) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  f"The number of training samples ({self.num_training_batches}) is smaller than the logging interval"


tensor(691.7720, grad_fn=<AddBackward0>)
tensor(455.2380, grad_fn=<AddBackward0>)
tensor(311.4327, grad_fn=<AddBackward0>)
tensor(497.8914, grad_fn=<AddBackward0>)
tensor(450.0844, grad_fn=<AddBackward0>)
tensor(758.4471, grad_fn=<AddBackward0>)
tensor(480.8900, grad_fn=<AddBackward0>)
tensor(199.5171, grad_fn=<AddBackward0>)
tensor(738.4958, grad_fn=<AddBackward0>)
tensor(614.6758, grad_fn=<AddBackward0>)


tensor(680.9463, grad_fn=<AddBackward0>)
tensor(447.7267, grad_fn=<AddBackward0>)
tensor(304.5118, grad_fn=<AddBackward0>)
tensor(489.3120, grad_fn=<AddBackward0>)
tensor(442.7922, grad_fn=<AddBackward0>)
tensor(746.2365, grad_fn=<AddBackward0>)
tensor(471.6473, grad_fn=<AddBackward0>)
tensor(194.2835, grad_fn=<AddBackward0>)
tensor(727.7947, grad_fn=<AddBackward0>)
tensor(603.6330, grad_fn=<AddBackward0>)


tensor(669.2836, grad_fn=<AddBackward0>)
tensor(439.7059, grad_fn=<AddBackward0>)
tensor(297.0364, grad_fn=<AddBackward0>)
tensor(479.9294, grad_fn=<AddBackward0>)
tensor(434.7564, grad_fn=<AddBackward0>)
tensor(732.4019, grad_fn=<AddBackward0>)
tensor(461.1431, grad_fn=<AddBackward0>)
tensor(188.3793, grad_fn=<AddBackward0>)
tensor(715.4551, grad_fn=<AddBackward0>)
tensor(590.6855, grad_fn=<AddBackward0>)


tensor(655.4183, grad_fn=<AddBackward0>)
tensor(430.3156, grad_fn=<AddBackward0>)
tensor(288.1779, grad_fn=<AddBackward0>)
tensor(468.7227, grad_fn=<AddBackward0>)
tensor(425.1605, grad_fn=<AddBackward0>)
tensor(715.3297, grad_fn=<AddBackward0>)
tensor(448.2183, grad_fn=<AddBackward0>)
tensor(181.2678, grad_fn=<AddBackward0>)
tensor(700.1208, grad_fn=<AddBackward0>)
tensor(574.4003, grad_fn=<AddBackward0>)


tensor(637.8298, grad_fn=<AddBackward0>)
tensor(418.7004, grad_fn=<AddBackward0>)
tensor(277.1320, grad_fn=<AddBackward0>)
tensor(454.6632, grad_fn=<AddBackward0>)
tensor(413.2782, grad_fn=<AddBackward0>)
tensor(693.2750, grad_fn=<AddBackward0>)
tensor(431.7521, grad_fn=<AddBackward0>)
tensor(172.6599, grad_fn=<AddBackward0>)
tensor(680.4493, grad_fn=<AddBackward0>)
tensor(553.3890, grad_fn=<AddBackward0>)


tensor(615.1155, grad_fn=<AddBackward0>)
tensor(404.2983, grad_fn=<AddBackward0>)
tensor(263.4440, grad_fn=<AddBackward0>)
tensor(437.0710, grad_fn=<AddBackward0>)
tensor(398.8393, grad_fn=<AddBackward0>)
tensor(664.8797, grad_fn=<AddBackward0>)
tensor(411.2045, grad_fn=<AddBackward0>)
tensor(163.0084, grad_fn=<AddBackward0>)
tensor(655.7122, grad_fn=<AddBackward0>)
tensor(526.9808, grad_fn=<AddBackward0>)


tensor(586.7850, grad_fn=<AddBackward0>)
tensor(387.4647, grad_fn=<AddBackward0>)
tensor(247.6808, grad_fn=<AddBackward0>)
tensor(416.3522, grad_fn=<AddBackward0>)
tensor(382.6728, grad_fn=<AddBackward0>)
tensor(630.1805, grad_fn=<AddBackward0>)
tensor(387.5226, grad_fn=<AddBackward0>)
tensor(154.1205, grad_fn=<AddBackward0>)
tensor(626.7336, grad_fn=<AddBackward0>)
tensor(496.2038, grad_fn=<AddBackward0>)


tensor(554.3761, grad_fn=<AddBackward0>)
tensor(370.0768, grad_fn=<AddBackward0>)
tensor(232.0167, grad_fn=<AddBackward0>)
tensor(394.6700, grad_fn=<AddBackward0>)
tensor(367.0680, grad_fn=<AddBackward0>)
tensor(591.5389, grad_fn=<AddBackward0>)
tensor(363.6667, grad_fn=<AddBackward0>)
tensor(149.0282, grad_fn=<AddBackward0>)
tensor(596.2845, grad_fn=<AddBackward0>)
tensor(464.0818, grad_fn=<AddBackward0>)


tensor(521.6248, grad_fn=<AddBackward0>)
tensor(355.0038, grad_fn=<AddBackward0>)
tensor(219.4873, grad_fn=<AddBackward0>)
tensor(375.0621, grad_fn=<AddBackward0>)
tensor(354.5389, grad_fn=<AddBackward0>)
tensor(552.9711, grad_fn=<AddBackward0>)
tensor(343.0845, grad_fn=<AddBackward0>)
tensor(149.9022, grad_fn=<AddBackward0>)
tensor(567.4373, grad_fn=<AddBackward0>)
tensor(433.8941, grad_fn=<AddBackward0>)


tensor(492.2534, grad_fn=<AddBackward0>)
tensor(343.7593, grad_fn=<AddBackward0>)
tensor(211.4086, grad_fn=<AddBackward0>)
tensor(358.8068, grad_fn=<AddBackward0>)
tensor(345.5328, grad_fn=<AddBackward0>)
tensor(517.9031, grad_fn=<AddBackward0>)
tensor(327.0471, grad_fn=<AddBackward0>)
tensor(155.7970, grad_fn=<AddBackward0>)
tensor(541.5709, grad_fn=<AddBackward0>)
tensor(407.4747, grad_fn=<AddBackward0>)


tensor(467.9734, grad_fn=<AddBackward0>)
tensor(335.5928, grad_fn=<AddBackward0>)
tensor(206.7128, grad_fn=<AddBackward0>)
tensor(345.2669, grad_fn=<AddBackward0>)
tensor(338.9357, grad_fn=<AddBackward0>)
tensor(488.3177, grad_fn=<AddBackward0>)
tensor(315.0085, grad_fn=<AddBackward0>)
tensor(164.0487, grad_fn=<AddBackward0>)
tensor(519.2498, grad_fn=<AddBackward0>)
tensor(385.7546, grad_fn=<AddBackward0>)


tensor(449.0665, grad_fn=<AddBackward0>)
tensor(329.4676, grad_fn=<AddBackward0>)
tensor(204.1358, grad_fn=<AddBackward0>)
tensor(334.1068, grad_fn=<AddBackward0>)
tensor(334.0151, grad_fn=<AddBackward0>)
tensor(464.9966, grad_fn=<AddBackward0>)
tensor(306.2475, grad_fn=<AddBackward0>)
tensor(172.3993, grad_fn=<AddBackward0>)
tensor(500.9777, grad_fn=<AddBackward0>)
tensor(369.0157, grad_fn=<AddBackward0>)


tensor(435.0021, grad_fn=<AddBackward0>)
tensor(324.7253, grad_fn=<AddBackward0>)
tensor(202.8272, grad_fn=<AddBackward0>)
tensor(325.2960, grad_fn=<AddBackward0>)
tensor(330.2337, grad_fn=<AddBackward0>)
tensor(447.4699, grad_fn=<AddBackward0>)
tensor(299.9559, grad_fn=<AddBackward0>)
tensor(179.2480, grad_fn=<AddBackward0>)
tensor(486.7286, grad_fn=<AddBackward0>)
tensor(356.5894, grad_fn=<AddBackward0>)


tensor(424.5381, grad_fn=<AddBackward0>)
tensor(320.7092, grad_fn=<AddBackward0>)
tensor(201.9885, grad_fn=<AddBackward0>)
tensor(318.4440, grad_fn=<AddBackward0>)
tensor(326.7993, grad_fn=<AddBackward0>)
tensor(434.2933, grad_fn=<AddBackward0>)
tensor(295.0628, grad_fn=<AddBackward0>)
tensor(183.5360, grad_fn=<AddBackward0>)
tensor(475.7035, grad_fn=<AddBackward0>)
tensor(347.1162, grad_fn=<AddBackward0>)


tensor(416.1081, grad_fn=<AddBackward0>)
tensor(316.6761, grad_fn=<AddBackward0>)
tensor(200.8132, grad_fn=<AddBackward0>)
tensor(312.7359, grad_fn=<AddBackward0>)
tensor(323.0188, grad_fn=<AddBackward0>)
tensor(423.8377, grad_fn=<AddBackward0>)
tensor(290.5813, grad_fn=<AddBackward0>)
tensor(185.0904, grad_fn=<AddBackward0>)
tensor(466.7709, grad_fn=<AddBackward0>)
tensor(339.3958, grad_fn=<AddBackward0>)


tensor(408.6628, grad_fn=<AddBackward0>)
tensor(312.2698, grad_fn=<AddBackward0>)
tensor(198.9809, grad_fn=<AddBackward0>)
tensor(307.5241, grad_fn=<AddBackward0>)
tensor(318.7730, grad_fn=<AddBackward0>)
tensor(415.0315, grad_fn=<AddBackward0>)
tensor(286.1025, grad_fn=<AddBackward0>)
tensor(184.6314, grad_fn=<AddBackward0>)
tensor(459.0320, grad_fn=<AddBackward0>)
tensor(332.7086, grad_fn=<AddBackward0>)


tensor(401.7737, grad_fn=<AddBackward0>)
tensor(307.5540, grad_fn=<AddBackward0>)
tensor(196.6395, grad_fn=<AddBackward0>)
tensor(302.4850, grad_fn=<AddBackward0>)
tensor(314.2302, grad_fn=<AddBackward0>)
tensor(407.2216, grad_fn=<AddBackward0>)
tensor(281.6014, grad_fn=<AddBackward0>)
tensor(183.1029, grad_fn=<AddBackward0>)
tensor(451.8861, grad_fn=<AddBackward0>)
tensor(326.5851, grad_fn=<AddBackward0>)


tensor(395.2252, grad_fn=<AddBackward0>)
tensor(302.7044, grad_fn=<AddBackward0>)
tensor(194.0594, grad_fn=<AddBackward0>)
tensor(297.4858, grad_fn=<AddBackward0>)
tensor(309.5581, grad_fn=<AddBackward0>)
tensor(399.9338, grad_fn=<AddBackward0>)
tensor(277.1230, grad_fn=<AddBackward0>)
tensor(181.2003, grad_fn=<AddBackward0>)
tensor(444.9433, grad_fn=<AddBackward0>)
tensor(320.7025, grad_fn=<AddBackward0>)


tensor(388.8409, grad_fn=<AddBackward0>)
tensor(297.8319, grad_fn=<AddBackward0>)
tensor(191.4281, grad_fn=<AddBackward0>)
tensor(292.4759, grad_fn=<AddBackward0>)
tensor(304.8632, grad_fn=<AddBackward0>)
tensor(392.8426, grad_fn=<AddBackward0>)
tensor(272.6720, grad_fn=<AddBackward0>)
tensor(179.2711, grad_fn=<AddBackward0>)
tensor(437.9849, grad_fn=<AddBackward0>)
tensor(314.8817, grad_fn=<AddBackward0>)


tensor(382.4919, grad_fn=<AddBackward0>)
tensor(292.9704, grad_fn=<AddBackward0>)
tensor(188.8248, grad_fn=<AddBackward0>)
tensor(287.4431, grad_fn=<AddBackward0>)
tensor(300.1803, grad_fn=<AddBackward0>)
tensor(385.7783, grad_fn=<AddBackward0>)
tensor(268.2275, grad_fn=<AddBackward0>)
tensor(177.3975, grad_fn=<AddBackward0>)
tensor(430.9305, grad_fn=<AddBackward0>)
tensor(309.0486, grad_fn=<AddBackward0>)


tensor(376.1042, grad_fn=<AddBackward0>)
tensor(288.1031, grad_fn=<AddBackward0>)
tensor(186.2497, grad_fn=<AddBackward0>)
tensor(282.3795, grad_fn=<AddBackward0>)
tensor(295.4818, grad_fn=<AddBackward0>)
tensor(378.6876, grad_fn=<AddBackward0>)
tensor(263.7595, grad_fn=<AddBackward0>)
tensor(175.5205, grad_fn=<AddBackward0>)
tensor(423.7705, grad_fn=<AddBackward0>)
tensor(303.1850, grad_fn=<AddBackward0>)


tensor(369.6438, grad_fn=<AddBackward0>)
tensor(283.1860, grad_fn=<AddBackward0>)
tensor(183.6578, grad_fn=<AddBackward0>)
tensor(277.2616, grad_fn=<AddBackward0>)
tensor(290.7129, grad_fn=<AddBackward0>)
tensor(371.5732, grad_fn=<AddBackward0>)
tensor(259.2289, grad_fn=<AddBackward0>)
tensor(173.5376, grad_fn=<AddBackward0>)
tensor(416.5027, grad_fn=<AddBackward0>)
tensor(297.2899, grad_fn=<AddBackward0>)


tensor(363.0906, grad_fn=<AddBackward0>)
tensor(278.1640, grad_fn=<AddBackward0>)
tensor(180.9887, grad_fn=<AddBackward0>)
tensor(272.0491, grad_fn=<AddBackward0>)
tensor(285.8157, grad_fn=<AddBackward0>)
tensor(364.4407, grad_fn=<AddBackward0>)
tensor(254.5907, grad_fn=<AddBackward0>)
tensor(171.3560, grad_fn=<AddBackward0>)
tensor(409.1068, grad_fn=<AddBackward0>)
tensor(291.3504, grad_fn=<AddBackward0>)


tensor(356.4142, grad_fn=<AddBackward0>)
tensor(272.9810, grad_fn=<AddBackward0>)
tensor(178.1872, grad_fn=<AddBackward0>)
tensor(266.6937, grad_fn=<AddBackward0>)
tensor(280.7330, grad_fn=<AddBackward0>)
tensor(357.2680, grad_fn=<AddBackward0>)
tensor(249.7966, grad_fn=<AddBackward0>)
tensor(168.9061, grad_fn=<AddBackward0>)
tensor(401.5386, grad_fn=<AddBackward0>)
tensor(285.3307, grad_fn=<AddBackward0>)


tensor(349.5635, grad_fn=<AddBackward0>)
tensor(267.5804, grad_fn=<AddBackward0>)
tensor(175.2061, grad_fn=<AddBackward0>)
tensor(261.1419, grad_fn=<AddBackward0>)
tensor(275.4061, grad_fn=<AddBackward0>)
tensor(350.0034, grad_fn=<AddBackward0>)
tensor(244.7928, grad_fn=<AddBackward0>)
tensor(166.1337, grad_fn=<AddBackward0>)
tensor(393.7310, grad_fn=<AddBackward0>)
tensor(279.1758, grad_fn=<AddBackward0>)


tensor(342.4677, grad_fn=<AddBackward0>)
tensor(261.8994, grad_fn=<AddBackward0>)
tensor(171.9995, grad_fn=<AddBackward0>)
tensor(255.3303, grad_fn=<AddBackward0>)
tensor(269.7703, grad_fn=<AddBackward0>)
tensor(342.5732, grad_fn=<AddBackward0>)
tensor(239.5152, grad_fn=<AddBackward0>)
tensor(162.9839, grad_fn=<AddBackward0>)
tensor(385.5950, grad_fn=<AddBackward0>)
tensor(272.8148, grad_fn=<AddBackward0>)


tensor(335.0361, grad_fn=<AddBackward0>)
tensor(255.8612, grad_fn=<AddBackward0>)
tensor(168.5129, grad_fn=<AddBackward0>)
tensor(249.1810, grad_fn=<AddBackward0>)
tensor(263.7465, grad_fn=<AddBackward0>)
tensor(334.8864, grad_fn=<AddBackward0>)
tensor(233.8839, grad_fn=<AddBackward0>)
tensor(159.3841, grad_fn=<AddBackward0>)
tensor(377.0198, grad_fn=<AddBackward0>)
tensor(266.1610, grad_fn=<AddBackward0>)


tensor(327.1534, grad_fn=<AddBackward0>)
tensor(249.3646, grad_fn=<AddBackward0>)
tensor(164.6716, grad_fn=<AddBackward0>)
tensor(242.5947, grad_fn=<AddBackward0>)
tensor(257.2312, grad_fn=<AddBackward0>)
tensor(326.8362, grad_fn=<AddBackward0>)
tensor(227.7959, grad_fn=<AddBackward0>)
tensor(155.2242, grad_fn=<AddBackward0>)
tensor(367.8734, grad_fn=<AddBackward0>)
tensor(259.1115, grad_fn=<AddBackward0>)


tensor(318.6795, grad_fn=<AddBackward0>)
tensor(242.2779, grad_fn=<AddBackward0>)
tensor(160.3739, grad_fn=<AddBackward0>)
tensor(235.4488, grad_fn=<AddBackward0>)
tensor(250.0958, grad_fn=<AddBackward0>)
tensor(318.3073, grad_fn=<AddBackward0>)
tensor(221.1309, grad_fn=<AddBackward0>)
tensor(150.3676, grad_fn=<AddBackward0>)
tensor(358.0143, grad_fn=<AddBackward0>)
tensor(251.5573, grad_fn=<AddBackward0>)


tensor(309.4707, grad_fn=<AddBackward0>)
tensor(234.4656, grad_fn=<AddBackward0>)
tensor(155.5224, grad_fn=<AddBackward0>)
tensor(227.6193, grad_fn=<AddBackward0>)
tensor(242.2175, grad_fn=<AddBackward0>)
tensor(309.1775, grad_fn=<AddBackward0>)
tensor(213.7859, grad_fn=<AddBackward0>)
tensor(144.7336, grad_fn=<AddBackward0>)
tensor(347.2886, grad_fn=<AddBackward0>)
tensor(243.3814, grad_fn=<AddBackward0>)


tensor(299.3879, grad_fn=<AddBackward0>)
tensor(225.8254, grad_fn=<AddBackward0>)
tensor(150.0688, grad_fn=<AddBackward0>)
tensor(218.9956, grad_fn=<AddBackward0>)
tensor(233.5096, grad_fn=<AddBackward0>)
tensor(299.2932, grad_fn=<AddBackward0>)
tensor(205.6815, grad_fn=<AddBackward0>)
tensor(138.3334, grad_fn=<AddBackward0>)
tensor(335.5089, grad_fn=<AddBackward0>)
tensor(234.4587, grad_fn=<AddBackward0>)


tensor(288.2840, grad_fn=<AddBackward0>)
tensor(216.2917, grad_fn=<AddBackward0>)
tensor(144.0128, grad_fn=<AddBackward0>)
tensor(209.4915, grad_fn=<AddBackward0>)
tensor(223.9284, grad_fn=<AddBackward0>)
tensor(288.5016, grad_fn=<AddBackward0>)
tensor(196.7662, grad_fn=<AddBackward0>)
tensor(131.2422, grad_fn=<AddBackward0>)
tensor(322.5110, grad_fn=<AddBackward0>)
tensor(224.6983, grad_fn=<AddBackward0>)


tensor(276.0442, grad_fn=<AddBackward0>)
tensor(205.8600, grad_fn=<AddBackward0>)
tensor(137.4058, grad_fn=<AddBackward0>)
tensor(199.0768, grad_fn=<AddBackward0>)
tensor(213.4804, grad_fn=<AddBackward0>)
tensor(276.6805, grad_fn=<AddBackward0>)
tensor(187.0336, grad_fn=<AddBackward0>)
tensor(123.5855, grad_fn=<AddBackward0>)
tensor(308.1841, grad_fn=<AddBackward0>)
tensor(214.0549, grad_fn=<AddBackward0>)


tensor(262.6075, grad_fn=<AddBackward0>)
tensor(194.5806, grad_fn=<AddBackward0>)
tensor(130.3232, grad_fn=<AddBackward0>)
tensor(187.7736, grad_fn=<AddBackward0>)
tensor(202.2070, grad_fn=<AddBackward0>)
tensor(263.7973, grad_fn=<AddBackward0>)
tensor(176.5201, grad_fn=<AddBackward0>)
tensor(115.4680, grad_fn=<AddBackward0>)
tensor(292.5276, grad_fn=<AddBackward0>)
tensor(202.5867, grad_fn=<AddBackward0>)


tensor(248.0259, grad_fn=<AddBackward0>)
tensor(182.5569, grad_fn=<AddBackward0>)
tensor(122.8399, grad_fn=<AddBackward0>)
tensor(175.6690, grad_fn=<AddBackward0>)
tensor(190.1980, grad_fn=<AddBackward0>)
tensor(249.9683, grad_fn=<AddBackward0>)
tensor(165.3279, grad_fn=<AddBackward0>)
tensor(106.9877, grad_fn=<AddBackward0>)
tensor(275.6923, grad_fn=<AddBackward0>)
tensor(190.4778, grad_fn=<AddBackward0>)


tensor(232.4922, grad_fn=<AddBackward0>)
tensor(169.9846, grad_fn=<AddBackward0>)
tensor(115.0761, grad_fn=<AddBackward0>)
tensor(162.9464, grad_fn=<AddBackward0>)
tensor(177.6306, grad_fn=<AddBackward0>)
tensor(235.4177, grad_fn=<AddBackward0>)
tensor(153.6521, grad_fn=<AddBackward0>)
tensor(98.3351, grad_fn=<AddBackward0>)
tensor(257.9496, grad_fn=<AddBackward0>)
tensor(178.0009, grad_fn=<AddBackward0>)


tensor(216.3193, grad_fn=<AddBackward0>)
tensor(157.1801, grad_fn=<AddBackward0>)
tensor(107.2457, grad_fn=<AddBackward0>)
tensor(149.8991, grad_fn=<AddBackward0>)
tensor(164.7910, grad_fn=<AddBackward0>)
tensor(220.4441, grad_fn=<AddBackward0>)
tensor(141.7893, grad_fn=<AddBackward0>)
tensor(89.8348, grad_fn=<AddBackward0>)
tensor(239.6701, grad_fn=<AddBackward0>)
tensor(165.4977, grad_fn=<AddBackward0>)


tensor(199.9277, grad_fn=<AddBackward0>)
tensor(144.5690, grad_fn=<AddBackward0>)
tensor(99.6449, grad_fn=<AddBackward0>)
tensor(136.9167, grad_fn=<AddBackward0>)
tensor(152.0593, grad_fn=<AddBackward0>)
tensor(205.4238, grad_fn=<AddBackward0>)
tensor(130.1149, grad_fn=<AddBackward0>)
tensor(81.8794, grad_fn=<AddBackward0>)
tensor(221.3314, grad_fn=<AddBackward0>)
tensor(153.3677, grad_fn=<AddBackward0>)


tensor(183.8264, grad_fn=<AddBackward0>)
tensor(132.6281, grad_fn=<AddBackward0>)
tensor(92.5855, grad_fn=<AddBackward0>)
tensor(124.4446, grad_fn=<AddBackward0>)
tensor(139.8522, grad_fn=<AddBackward0>)
tensor(190.8055, grad_fn=<AddBackward0>)
tensor(119.0347, grad_fn=<AddBackward0>)
tensor(74.8207, grad_fn=<AddBackward0>)
tensor(203.5170, grad_fn=<AddBackward0>)
tensor(142.0383, grad_fn=<AddBackward0>)


tensor(168.5760, grad_fn=<AddBackward0>)
tensor(121.8109, grad_fn=<AddBackward0>)
tensor(86.3257, grad_fn=<AddBackward0>)
tensor(112.9256, grad_fn=<AddBackward0>)
tensor(128.5633, grad_fn=<AddBackward0>)
tensor(177.0602, grad_fn=<AddBackward0>)
tensor(108.9302, grad_fn=<AddBackward0>)
tensor(68.9154, grad_fn=<AddBackward0>)
tensor(186.8478, grad_fn=<AddBackward0>)
tensor(131.8940, grad_fn=<AddBackward0>)


tensor(154.7087, grad_fn=<AddBackward0>)
tensor(112.4802, grad_fn=<AddBackward0>)
tensor(81.0443, grad_fn=<AddBackward0>)
tensor(102.7318, grad_fn=<AddBackward0>)
tensor(118.5181, grad_fn=<AddBackward0>)
tensor(164.5857, grad_fn=<AddBackward0>)
tensor(100.1038, grad_fn=<AddBackward0>)
tensor(64.3234, grad_fn=<AddBackward0>)
tensor(171.8490, grad_fn=<AddBackward0>)
tensor(123.1830, grad_fn=<AddBackward0>)


tensor(142.6122, grad_fn=<AddBackward0>)
tensor(104.8421, grad_fn=<AddBackward0>)
tensor(76.8298, grad_fn=<AddBackward0>)
tensor(94.1012, grad_fn=<AddBackward0>)
tensor(109.9259, grad_fn=<AddBackward0>)
tensor(153.6235, grad_fn=<AddBackward0>)
tensor(92.7206, grad_fn=<AddBackward0>)
tensor(61.0607, grad_fn=<AddBackward0>)
tensor(158.8458, grad_fn=<AddBackward0>)
tensor(115.9618, grad_fn=<AddBackward0>)


tensor(132.4497, grad_fn=<AddBackward0>)
tensor(98.8857, grad_fn=<AddBackward0>)
tensor(73.6283, grad_fn=<AddBackward0>)
tensor(87.0848, grad_fn=<AddBackward0>)
tensor(102.8241, grad_fn=<AddBackward0>)
tensor(144.2515, grad_fn=<AddBackward0>)
tensor(86.7659, grad_fn=<AddBackward0>)
tensor(58.9275, grad_fn=<AddBackward0>)
tensor(147.9462, grad_fn=<AddBackward0>)
tensor(110.1130, grad_fn=<AddBackward0>)


tensor(124.1703, grad_fn=<AddBackward0>)
tensor(94.3786, grad_fn=<AddBackward0>)
tensor(71.2194, grad_fn=<AddBackward0>)
tensor(81.5378, grad_fn=<AddBackward0>)
tensor(97.0698, grad_fn=<AddBackward0>)
tensor(136.4020, grad_fn=<AddBackward0>)
tensor(82.0594, grad_fn=<AddBackward0>)
tensor(57.5599, grad_fn=<AddBackward0>)
tensor(139.0483, grad_fn=<AddBackward0>)
tensor(105.3889, grad_fn=<AddBackward0>)


tensor(117.5414, grad_fn=<AddBackward0>)
tensor(90.9453, grad_fn=<AddBackward0>)
tensor(69.3006, grad_fn=<AddBackward0>)
tensor(77.1796, grad_fn=<AddBackward0>)
tensor(92.4042, grad_fn=<AddBackward0>)
tensor(129.8753, grad_fn=<AddBackward0>)
tensor(78.3209, grad_fn=<AddBackward0>)
tensor(56.5661, grad_fn=<AddBackward0>)
tensor(131.8647, grad_fn=<AddBackward0>)
tensor(101.4746, grad_fn=<AddBackward0>)


tensor(112.2074, grad_fn=<AddBackward0>)
tensor(88.1782, grad_fn=<AddBackward0>)
tensor(67.5913, grad_fn=<AddBackward0>)
tensor(73.6845, grad_fn=<AddBackward0>)
tensor(88.5338, grad_fn=<AddBackward0>)
tensor(124.4010, grad_fn=<AddBackward0>)
tensor(75.2517, grad_fn=<AddBackward0>)
tensor(55.6223, grad_fn=<AddBackward0>)
tensor(126.0194, grad_fn=<AddBackward0>)
tensor(98.0741, grad_fn=<AddBackward0>)


tensor(107.7931, grad_fn=<AddBackward0>)
tensor(85.7330, grad_fn=<AddBackward0>)
tensor(65.8852, grad_fn=<AddBackward0>)
tensor(70.7578, grad_fn=<AddBackward0>)
tensor(85.1930, grad_fn=<AddBackward0>)
tensor(119.7103, grad_fn=<AddBackward0>)
tensor(72.5980, grad_fn=<AddBackward0>)
tensor(54.5200, grad_fn=<AddBackward0>)
tensor(121.1504, grad_fn=<AddBackward0>)
tensor(94.9678, grad_fn=<AddBackward0>)


tensor(103.9866, grad_fn=<AddBackward0>)
tensor(83.3793, grad_fn=<AddBackward0>)
tensor(64.0686, grad_fn=<AddBackward0>)
tensor(68.1781, grad_fn=<AddBackward0>)
tensor(82.1820, grad_fn=<AddBackward0>)
tensor(115.5768, grad_fn=<AddBackward0>)
tensor(70.1811, grad_fn=<AddBackward0>)
tensor(53.1755, grad_fn=<AddBackward0>)
tensor(116.9578, grad_fn=<AddBackward0>)
tensor(92.0214, grad_fn=<AddBackward0>)


tensor(100.5625, grad_fn=<AddBackward0>)
tensor(81.0022, grad_fn=<AddBackward0>)
tensor(62.1156, grad_fn=<AddBackward0>)
tensor(65.8035, grad_fn=<AddBackward0>)
tensor(79.3738, grad_fn=<AddBackward0>)
tensor(111.8295, grad_fn=<AddBackward0>)
tensor(67.8954, grad_fn=<AddBackward0>)
tensor(51.5988, grad_fn=<AddBackward0>)
tensor(113.2155, grad_fn=<AddBackward0>)
tensor(89.1671, grad_fn=<AddBackward0>)


tensor(97.3737, grad_fn=<AddBackward0>)
tensor(78.5694, grad_fn=<AddBackward0>)
tensor(60.0548, grad_fn=<AddBackward0>)
tensor(63.5532, grad_fn=<AddBackward0>)
tensor(76.6975, grad_fn=<AddBackward0>)
tensor(108.3477, grad_fn=<AddBackward0>)
tensor(65.6864, grad_fn=<AddBackward0>)
tensor(49.8464, grad_fn=<AddBackward0>)
tensor(109.7655, grad_fn=<AddBackward0>)
tensor(86.3780, grad_fn=<AddBackward0>)


In [ ]:
# # Neural Network 
# # Pytroch lighting 
# class model(pl.LightningModule):
#   def __init__(self):
#     super(model, self).__init__() 
#     self.fc1 = nn.linear(input_size, hidden_size_1)
#     self.fc2 = nn.Linear(hidden_size_1, hidden_size_2)
#     self.out = nn.Linear(hidden_size_2, output_size)
#     self.lr = 0.001
#     self.loss_1 = nn.MSELoss() # lOSS OF THE LABELS ALONE 
#     self.loss_2 = nn.MSEloss() # LOSS OF FIRST ORDER DIFFERENTIAL LABELS AND LABELS TOGETHER. 

# # 3 layer NEURAL NETWORK
# def forward(self, x):
#   batch_size, _ = x.size() # this is subject to change depends on input data 
#   x = x.view(batch_size, -1)
#   x = F.softplus(self.fc1)
#   x = F.softplus(self.fc2)
#   return self.out(x) 

# def configure_optimizers(self):
#   return Adam(self.paramters(), lr = self.lr) # return adam 

# def training_step(self, train_batch): 
#   x , y = train_batch  
#   prediction_prices = self.forward(x)
#   loss = alpha* self.loss_1(prediction_prices, y) + beta * self.loss_2


# class Data(plt.LightningModule):
#   def prepare_data(self):
#     self.









# # Back prop / losss 


# # Training 
# #validation 

In [ ]:
# class NeuralNet(nn.Module):
#   def __init__(self, input_size, hidden_size_1, hidden_size_2, output_size): 
#     super(NeuralNet, self).__init__()
#     self.layer_1 = nn.Linear(input_size, hidden_size_1) # linear layer
#     self.layer_2 = nn.Linear(hidden_size_1, hidden_size_2)
#     self.layer_3 = nn.Linear(hidden_size_2, output_size)

# # 3 layer MLP forward pass
#   def forward(self, x):
#     # layer 1
#     x = self.layer_1(x)
#     x = torch.Softplus(x)

#     # layer 2
#     x = self.layer_2(x)
#     x = torch.Softplus(x)

#     # layer 3 
#     x = self.layer_3(x)

#     return  x 